### ISSUE TITLE
terragrunt S3 backend permission error when using from another aws account

### ISSUE THREAD

**Issue by truptiak** [gruntwork-io/terragrunt#745] opened 2019-06-13 04:13 UTC
I am using two accounts as MainAWS account & TestAWS account. We have created the bucket in MainAWS account as "xxxxxbucket". Also created dynamodb table as "tf-state-lock" with LockID.

Created the below structure to use my module with terragrunt & keep my remote backend config DRY -

# tree
.
├── non-prod
│   ├
│   └── us-east-1
│       └── vpc
│           └── terraform.tfvars
├── README.md
└── terraform.tfvars

root level terraform.tfvars as below :

terragrunt = {
  terraform {
    source = "."
  }

  # Configure Terragrunt to automatically store tfstate files in an S3 bucket

  remote_state {
    backend = "s3"

    config {
      encrypt = true
      bucket  = "xxxxxbucket"
      key     = "${path_relative_to_include()}/terraform.tfstate"
      region  = "us-east-1"

     dynamodb_table                 = "tf-state-lock"
     enable_lock_table_ssencryption = true

      skip_bucket_versioning      = true
      skip_bucket_ssencryption    = true
      skip_bucket_accesslogging   = true
      skip_region_validation      = true
      skip_credentials_validation = true
      skip_metadata_api_check     = true
      force_path_style            = true
     }	
    }
  }
}

Child level terraform.tfvars as below : 
terragrunt = {
  terraform {
       source = "git::ssh://git@gitlab.aws.exoduspoint.com:2222/core-infrastructure/terraform-modules.git//aws/vpc/?ref=master"
  }

# Include all settings from the root terraform.tfvars file

  include {
    path = "${find_in_parent_folders()}"
  }
}

# These are the variables we have to pass in to use the module specified in the terragrunt configuration above

 name   = "my-vpc"
 cidr = "10.0.0.0/16"
 aws_region = "us-east-1"

Attached below policy to my terraform user in account TestAWS -

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowCreateAndListS3ActionsOnSpecifiedTerragruntBucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketVersioning",
                "s3:CreateBucket"
            ],
            "Resource": "arn:aws:s3:::xxxxxbucket"
        },
        {
            "Sid": "AllowGetAndPutS3ActionsOnSpecifiedTerragruntBucketPath",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::xxxxxbucket/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:PutItem",
                "dynamodb:GetItem",
                "dynamodb:DescribeTable",
                "dynamodb:DeleteItem",
                "dynamodb:CreateTable"
            ],
            "Resource": "arn:aws:dynamodb:*:*:table/tf-state-lock"
        }
    ]
}

Attached below bucket level policy to the bucket in MainAWS account -

{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::accountID:user/terraform"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::xxxxxbucket"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::accountID:user/terraform"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::xxxxxbucket/tfstate"
        }
    ]
}

Now when finally I am running the terragrunt command,it's showing access denied error as below -

terragrunt-vpc-example/non-prod/us-east-1/vpc] 2019/06/13 04:09:14 Initializing remote state for the s3 backend
[terragrunt] 2019/06/13 04:09:14 AccessDenied: Access Denied
        status code: 403, request id: 7A56E5635D767A4A, host id: m1cKlNOEnB3X8Jd7gscjg6IS9hr4EEsX36J2/qLb0NDOWL+Uygt1TtuYoBnUj7srCOl0iMu9dF4=
[terragrunt] 2019/06/13 04:09:14 Unable to determine underlying exit code, so Terragrunt will exit with error code 1

1. With aws cli I can upload/download to the bucket.
2. When I am using the bucket from same account as TestAWS,its working fine.I have to change just bucket name.

3. Without terragrunt, I can able to use the s3 from MainAWS account as backend.

Is there anything which need to be added to my setup to make it working ?

**Comment by brikis98** [comment] 2019-06-14 11:31
What version of Terragrunt are you using?

**Comment by truptiak** [comment] 2019-06-17 03:45
I am using terragrunt version v0.18.7.

**Comment by brikis98** [comment] 2019-06-17 20:53
Could you fix the syntax highlighting on your code? It's hard to read it without any. You need to wrap each code block with three backticks: https://guides.github.com/features/mastering-markdown/

Are you sure you're using the same bucket name when testing with the `aws` CLI and in your `terraform.tfvars`? What commands are you running? How are you authenticating?

**Comment by mattiarossi** [comment] 2019-08-29 06:34
I think the issue is in the [checkIfVersioningEnabled](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L325) function that calls the s3.GetBucketVersioningInput function.
It looks like only the bucket owner can call that [API function](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETversioningStatus.html
):

`
GET Bucket versioning
Description
This implementation of the GET operation uses the versioning subresource to return the versioning state of a bucket. To retrieve the versioning state of a bucket, you must be the bucket owner.

`

A quick fix for this would be to use the skip_bucket_versioning flag and avoid calling checkIfVersioningEnabled if it is set to false. 

If that's an accepted solution, I can provide a PR.

**Comment by eamonnotoole** [comment] 2019-09-20 15:34
@mattiarossi @brikis98 I seem to be hitting this same problem.  I'm also trying to use a bucket created by another user for S3 state, and I also fail on checkIfVersioningEnabled().  I don't understand why terragrunt fails when running terraform directly succeeds.  It is a massive stumbling block for us.  We really want to use terragrunt, but we're going to have to use a patched version to get over this issue.

**Comment by yorinasub17** [comment] 2019-09-20 22:16
> A quick fix for this would be to use the skip_bucket_versioning flag and avoid calling checkIfVersioningEnabled if it is set to false.
> If that's an accepted solution, I can provide a PR.

Yes definitely should not do any versioning check if that flag is set to true. PR is very welcome for that change.

**Comment by mattiarossi** [comment] 2019-09-21 14:44
Hi, I have a patched 0.18 version available here: https://github.com/mattiarossi/terragrunt/releases/tag/v0.18.9
It is the latest v0.18.8 plus the skip_bucket_versioning check and the ability to use a local dynamodb endpoint
Will provide a PR for the master branch of terragrunt soon

**Comment by eamonnotoole** [comment] 2019-09-23 09:48
@mattiarossi Thanks, I'll hold off on putting up a PR.

**Comment by mattiarossi** [comment] 2019-09-23 13:57
@eamonnotoole PR has been created: https://github.com/gruntwork-io/terragrunt/pull/874

**Closed** 2019-09-24 09:20 UTC
Labels: question
