### ISSUE TITLE
Official docker image request 

### ISSUE THREAD

**Issue by smitthakkar96** [gruntwork-io/terragrunt#1831] opened 2021-09-28 17:33 UTC
Currently people have to rely on https://hub.docker.com/r/alpine/terragrunt for using terragrunt in docker if they don't want the hassle of building their own images. It looks like Terragrunt maintainers have been releasing patches quite frequently and new patches aren't available immediately to docker users as the alpine CircleCI job runs nightly and occasionally fails. It would be great if gruntworks takes care of rolling out docker images when releasing new version of Terragrunt.

**Comment by yorinasub17** [comment] 2021-09-30 22:35
Ah this is a duplicate of https://github.com/gruntwork-io/terragrunt/issues/1655. Please follow that ticket for this feature. Thanks!

**Closed by yorinasub17** 2021-09-30 22:35 UTC
