### ISSUE TITLE
terraform question output is hidden until after question is answered

### ISSUE THREAD

**Issue by grimm26** [gruntwork-io/terragrunt#585] opened 2018-10-11 18:38 UTC
starting with terragrunt 0.17.0 I hit this bug where when terraform asks a question, like confirming an apply, you can't see the question until after you have answered it.  It looks like it has stalled, but it is really just waiting for you to answer a question.

**Comment by grimm26** [comment] 2018-10-11 18:38
![screen shot 2018-10-11 at 1 21 52 pm](https://user-images.githubusercontent.com/127401/46826189-f969a080-cd5a-11e8-865f-309dbbfd4824.png)
![screen shot 2018-10-11 at 1 36 47 pm](https://user-images.githubusercontent.com/127401/46826194-fcfd2780-cd5a-11e8-9832-7b9986656396.png)

**Comment by lorengordon** [comment] 2018-10-11 18:41
I've also been seeing this...

**Comment by brikis98** [comment] 2018-10-12 10:41
Hm, this may be related to the recent stdout/stderr changes from #583... I'm not going to be able to look at this for a few days, but if anyone has a few minutes, this method would probably be my starting point: https://github.com/gruntwork-io/terragrunt/blob/master/shell/run_shell_cmd.go#L184

**Comment by autero1** [comment] 2018-10-15 21:03
I'll take a look.

**Comment by autero1** [comment] 2018-10-15 23:31
The problem is indeed in the `readStdoutAndStderr`. The `bufio.Scanner` default split function (`ScanLines`) scans line by line and we get a newline only after the user answers the `Enter a value:` prompt. We have a couple of options: 

1. Change the split function to `ScanBytes`
2. Use `io.MultiWriter` and `io.Copy` like here: https://github.com/kjk/go-cookbook/blob/master/advanced-exec/03-live-progress-and-capture-v3.go

Based on a quick test both seem to work. I'm leaning towards option 1 as it involves making only minor modifications. 

Don't know if it's a valid concern, but with the byte (instead of lines) scanning and concurrent stdout/err writes, could the captured output be corrupt?

**Comment by brikis98** [comment] 2018-10-16 00:11
@autero1 A big thank you for looking into this!

> Use io.MultiWriter and io.Copy like here: https://github.com/kjk/go-cookbook/blob/master/advanced-exec/03-live-progress-and-capture-v3.go

Oh, man, nice find. This definitely looks like the right approach to use for what we're doing. How big of a change would it be?

> Don't know if it's a valid concern, but with the byte (instead of lines) scanning and concurrent stdout/err writes, could the captured output be corrupt?

Yea, I worry it would be. If you read some random number of bytes, you might parse half a word or even half a letter, which would lead to very messy output.

**Comment by autero1** [comment] 2018-10-16 00:42
Not a very big change. Already tested with an quick-and-dirty copy-paste that it works. However, not really sure it would solve the byte reading problem.

**Comment by autero1** [comment] 2018-10-16 12:10
> Use io.MultiWriter and io.Copy
In the end I wasn't able to find a reason why using the io.Copy was necessary. Ended up removing a lot of code in favor of the MultiWriter.

**Comment by brikis98** [comment] 2018-10-16 13:19
Should be fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.17.1. Thank you @autero1!

**Closed by brikis98** 2018-10-16 13:19 UTC
Labels: bug, help wanted
