### ISSUE TITLE
exec.ExitError exit status 126.

### ISSUE THREAD

**Issue by Pacobart** [gruntwork-io/terragrunt#922] opened 2019-10-21 18:21 UTC
When I try to run ```terragrunt plan``` I'm getting a 126 error exit code. I've enabled debug logging and it's not very helpful. This same setup works perfectly on ubuntu. My guess is I'm missing a dependency. Is there somewhere I can get more detailed logging to show specifics?

Setup:
Arch Linux (Jenkins Agent openjdk image)
Terraform v0.12.12 (tried back to 0.12.9)
Terragrunt v0.20.5 (tried back to 0.19.26)

Command:
```terragrunt plan```

Error:
[terragrunt] 2019/10/21 17:56:27 Reading Terragrunt config file at /home/jenkins/git/terraform/dev-066184555952/development/aws.jenkins.canary/terragrunt.hcl
[terragrunt] 2019/10/21 17:56:27 Did not find any locals block: skipping evaluation.
[terragrunt] 2019/10/21 17:56:27 Did not find any locals block: skipping evaluation.
[terragrunt] [/home/jenkins/git/terraform/dev-066184555952/development/aws.jenkins.canary] 2019/10/21 17:56:27 Running command: terraform --version
[terragrunt] 2019/10/21 17:56:27 *exec.ExitError exit status 126
/go/src/github.com/gruntwork-io/terragrunt/shell/run_shell_cmd.go:93 (0x995c09)
/go/src/github.com/gruntwork-io/terragrunt/shell/run_shell_cmd.go:34 (0x9954a2)
/go/src/github.com/gruntwork-io/terragrunt/cli/version_check.go:25 (0xce3528)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:251 (0xcdc921)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:225 (0xcdc801)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:206 (0xcdc52e)
/go/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:490 (0xc79d28)
/go/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:264 (0xc77f9d)
/go/src/github.com/gruntwork-io/terragrunt/main.go:23 (0xce4e74)
/usr/local/go/src/runtime/proc.go:201 (0x42c1b7)
/usr/local/go/src/runtime/asm_amd64.s:1333 (0x457fe1)

**Comment by yorinasub17** [comment] 2019-10-21 18:33
Hi, exit code 126 is a permission denied error for execute permissions. Does the `terraform` binary have the execute bit turned on for the user?

**Comment by Pacobart** [comment] 2019-10-21 20:54
@yorinasub17 Even running as root it still doesn't fix this. I can run ```terraform --verion``` and ```terragrunt --version``` fine as the same user. Maybe I'm missing something about the execute bit?

**Comment by yorinasub17** [comment] 2019-10-21 21:02
So what is failing is the `exec` syscall to `terraform`. There isn't more logs to provide, because the issue is sufficiently captured by `*exec.ExitError exit status 126`.

So a few possibilities here:

- Is `terraform` a shell alias instead of an actual binary in the `PATH`?
- Is `terraform` a symlink instead of an actual binary?
- Is `terraform` resolving to different binaries between the execution environment of jenkins and when you manually run it?

You can also try to workaround this by directly passing in the absolute path to the `terraform` binary using [terraform_binary](https://github.com/gruntwork-io/terragrunt#terraform_binary).

**Comment by Pacobart** [comment] 2019-10-21 21:22
I'm using a terraform (github.com/tfutils/tfenv) and terragrunt (github.com/cunymatthieu/tgenv) version manager projects. Per their documentation I created a symlink to the binary folders. I've also tried using terraform_binary. Am I doing this correctly?
```terragrunt plan --terragrunt-tfpath=~/tfenv/bin/terraform```

I've installed terraform/terragrunt via the github projects successfully on MAC, CentOS and Ubuntu all working. When integrating into the Jenkins Agent (openjdk) image, I get the errors.

**Comment by yorinasub17** [comment] 2019-10-21 21:37
IIRC, `--terragrunt-tfpath` doesn't expand the home path so you will need to replace `~`.

If you are using `tfenv`, I would actually try pointing directly at the terraform binary (instead of the shim), just to make sure the 126 exit code is from the binary and not the shim.

One of the key requirements of `tfenv` is to add `~/tfenv/bin` to the `PATH` var as a part of the `bash_profile`/`zshenv`/etc. I am not sure jenkins opens a login shell for bash or zsh such that it goes through that, so I would double check if the PATH var is set correctly in the environment where you are getting your errors. Also, IIRC, `tfenv` usually installs the binaries and set the exec bit just for the user that ran `tfenv install`, so that might be the problem. You should check which users/groups owns the `terraform` shim and binary, and check which users have permissions to execute it and make sure it aligns with the user of the agent.

**Comment by Pacobart** [comment] 2019-10-22 19:54
I found by going to the full image (previously using an alpine version) my issue went away.

**Comment by yorinasub17** [comment] 2019-10-31 15:37
Thanks for closing the loop. Marking this as resolved.

**Closed by yorinasub17** 2019-10-31 15:37 UTC
Labels: question
