### ISSUE TITLE
terragrunt plan -out into current working dir?

### ISSUE THREAD

**Issue by esn89** [gruntwork-io/terragrunt#1601] opened 2021-03-22 23:03 UTC
I am using Terragrunt 0.21.6 and I am trying to get it working with https://github.com/runatlantis/atlantis

I would like to be able to output my plan file into the current working directory and not into a cache directory like so:
`.terragrunt-cache/U7G6F5F4V_9Kh2H/$planfilename.tfplan`

I would like to be able to specify a place to put the plan, and if I cannot, just any where that isn't in the `.terragrunt-cache` directory is fine.  I tried it with the `-out` and it doesn't seem to do what I want it to.

Any help would be appreciated.

**Comment by brikis98** [comment] 2021-03-23 09:58
> I would like to be able to specify a place to put the plan, and if I cannot, just any where that isn't in the `.terragrunt-cache` directory is fine. I tried it with the `-out` and it doesn't seem to do what I want it to.

What did you try and what did it do?

**Comment by esn89** [comment] 2021-03-23 17:08
What I tried to do is:

`terragrunt plan $(pwd)/test.tfplan`
And I get an output like:
```This plan was saved to: /my/desired/directory/test.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/my/desired/directory/test.tfplan"
 ```

It works and in my current directory I see a file named `test.tfplan`.

What happens is that the apply doesn't work:

`terragrunt apply $(pwd)/test.tfplan`  nor `terragrunt apply ./test.tfplan` nor `terragrunt apply /my/desired/directory/test.tfplan`.  Any of these three don't work.  I get an error which says:

```Too many command line arguments. Configuration path expected.
[terragrunt] 2021/03/23 17:02:03 Hit multiple errors:
exit status 1```

**Comment by brikis98** [comment] 2021-03-24 09:59
Could you post the full `terragrunt apply <PLAN>` command you're running _and_ the full log output? Also, please turn the [log level up](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-log-level).

**Comment by esn89** [comment] 2021-03-24 18:11
Sure:

The first way didn't quite work:

```
terragrunt apply test.tfplan --terragrunt-log-level=trace
Created log entry.
[terragrunt] 2021/03/24 18:04:39 Reading Terragrunt config file at /my/desired/directory/iam/terragrunt.hcl
[terragrunt] [/my/desired/directory/iam] 2021/03/24 18:04:39 Running command: terraform --version
[terragrunt] 2021/03/24 18:04:39 WARNING: no double-slash (//) found in source URL /root/deployment/infra/resources/modules/iam. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2021/03/24 18:04:39 Downloading Terraform configurations from file:///root/deployment/infra/resources/modules/iam into /my/desired/directory/iam/.terragrunt-cache/NeFkClsN2EdepIe6dPn_fphls_E/ZglRs72-h59bhO0NDWvIEqgWwVg
[terragrunt] 2021/03/24 18:04:39 Copying files from /my/desired/directory/iam into /my/desired/directory/iam/.terragrunt-cache/NeFkClsN2EdepIe6dPn_fphls_E/ZglRs72-h59bhO0NDWvIEqgWwVg
[terragrunt] 2021/03/24 18:04:39 Setting working directory to /my/desired/directory/iam/.terragrunt-cache/NeFkClsN2EdepIe6dPn_fphls_E/ZglRs72-h59bhO0NDWvIEqgWwVg
[terragrunt] 2021/03/24 18:04:42 Running command: terraform apply -var credentials=/my/desired/directory/iam/../../../credentials.json -var state_bucket_prefix=devtest -var-file /my/desired/directory/iam/../../common.tfvars -var-file /my/desired/directory/iam/../environment.tfvars test.tfplan --terragrunt-log-level=trace
Too many command line arguments. Configuration path expected.
[terragrunt] 2021/03/24 18:04:42 Hit multiple errors:
exit status 1
```

I re-ran it with this:
`TERRAGRUNT_DEBUG=true TG_LOG=debug terragrunt apply test.tfplan`
And got a trace:

```
Created log entry.
[terragrunt] 2021/03/24 18:05:21 Reading Terragrunt config file at /my/desired/directory/iam/terragrunt.hcl
[terragrunt] [/my/desired/directory/iam] 2021/03/24 18:05:21 Running command: terraform --version
[terragrunt] 2021/03/24 18:05:21 WARNING: no double-slash (//) found in source URL /root/deployment/infra/resources/modules/iam. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2021/03/24 18:05:21 Downloading Terraform configurations from file:///root/deployment/infra/resources/modules/iam into /my/desired/directory/iam/.terragrunt-cache/NeFkClsN2EdepIe6dPn_fphls_E/ZglRs72-h59bhO0NDWvIEqgWwVg
[terragrunt] 2021/03/24 18:05:21 Copying files from /my/desired/directory/iam into /my/desired/directory/iam/.terragrunt-cache/NeFkClsN2EdepIe6dPn_fphls_E/ZglRs72-h59bhO0NDWvIEqgWwVg
[terragrunt] 2021/03/24 18:05:21 Setting working directory to /my/desired/directory/iam/.terragrunt-cache/NeFkClsN2EdepIe6dPn_fphls_E/ZglRs72-h59bhO0NDWvIEqgWwVg
[terragrunt] 2021/03/24 18:05:24 Running command: terraform apply credentials=/my/desired/directory/iam/../../../credentials.json state_bucket_prefix=devtest /my/desired/directory/iam/../../common.tfvars /my/desired/directory/iam/../environment.tfvars test.tfplan
Too many command line arguments. Configuration path expected.
[terragrunt] 2021/03/24 18:05:25 errors.MultiError Hit multiple errors:
exit status 1
/go/src/github.com/gruntwork-io/terragrunt/errors/multierror.go:24 (0x6c70b2)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:458 (0xd0053c)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:439 (0xd001f7)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:327 (0xcfeeeb)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:229 (0xcfe9a1)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:210 (0xcfe6ce)
/go/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:490 (0xc9ba88)
/go/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:264 (0xc99cfd)
/go/src/github.com/gruntwork-io/terragrunt/main.go:27 (0xd071b1)
/usr/local/go/src/runtime/proc.go:201 (0x42c1b7)
/usr/local/go/src/runtime/asm_amd64.s:1333 (0x457fe1)
```

I hope this helps

**Comment by brikis98** [comment] 2021-03-25 10:29
Oh, looks like you're using `extra_arguments`. This may be a duplicate of #454 in that case. If you remove those, does the error go away? I understand those args are important, so you'd still need a fix for #454, but it would be helpful to understand if that's the issue here.

**Comment by brikis98** [comment] 2021-03-31 09:33
Ah, OK, thanks for confirming. Then this is a duplicate of https://github.com/gruntwork-io/terragrunt/issues/454. I'll close in favor of that issue.

**Closed by brikis98** 2021-03-31 09:33 UTC
Labels: question

**Comment by esn89** [comment] 2021-03-31 17:38
@brikis98 

No worries, thanks for looking in.  Has a fix been released for this?  Or perhaps in a newer version of Terragrunt?
