### ISSUE TITLE
terragrunt plan fails on new outputs if dependent module has already been applied

### ISSUE THREAD

**Issue by umairidris** [gruntwork-io/terragrunt#1140] opened 2020-04-15 20:31 UTC
Example:
- suppose module "B" depends on module "A"
- module A and B are applied
- module B now needs a new value from module A
- module A adds new output, and module B will add a new input to ingest this value
- run terragrunt plan or plan-all in module B

Got:  Unsupported attribute; This object does not have an attribute named "foo"

Want: mock output is used in the plan

Reason: If the module was already applied it exits fast and only returns the outputs from the applied module: https://github.com/gruntwork-io/terragrunt/blob/706b641dd6033cb556ec710237edc6241e75b5fc/config/dependency.go#L240

Possible change: merge the output and mock_outputs

**Comment by yorinasub17** [comment] 2020-04-15 20:36
Hi thanks for reporting this. This is actually a duplicate of https://github.com/gruntwork-io/terragrunt/issues/940 and https://github.com/gruntwork-io/terragrunt/issues/1127. Please follow those tickets for updates on the proposed features, which will (hopefully) address your use case. If not, please comment there so we have the information in there. Thanks!

**Closed by yorinasub17** 2020-04-15 20:36 UTC
