### ISSUE TITLE
terragrunt plan-all is flakey from 0.19.25

### ISSUE THREAD

**Issue by dvulpe** [gruntwork-io/terragrunt#904] opened 2019-10-09 20:35 UTC
Hi 

We recently noticed that terragrunt plan-all is flakey and would randomly fail with files not found errors, sometimes reporting that a terraform backend hasn't been configured, despite being configured correctly:
```
.terragrunt-cache/yZpa9oXGPFA9yBeYJLKvMDWHQLA/nOHeCNZgRObX4kF5VK1jboCrx_w/.terragrunt-module-manifest: no such file or directory
```

I wrote a test to reproduce the problem and if the subtest runs 100 times I get to reproduce the problem at least twice (this can be run in `integration_test.go` on the master branch):

```
func TestDependencyPlanAllFlake(t *testing.T) {

	cleanupTerraformFolder(t, TEST_FIXTURE_GET_OUTPUT)
	tmpEnvPath := copyEnvironment(t, TEST_FIXTURE_GET_OUTPUT)
	rootPath := util.JoinPath(tmpEnvPath, TEST_FIXTURE_GET_OUTPUT, "localstate", "live")

	stdout := bytes.Buffer{}
	stderr := bytes.Buffer{}
	err := runTerragruntCommand(
		t,
		fmt.Sprintf("terragrunt apply-all --terragrunt-non-interactive --terragrunt-working-dir %s", rootPath),
		&stdout,
		&stderr,
	)
	logBufferContentsLineByLine(t, stdout, "stdout")
	logBufferContentsLineByLine(t, stderr, "stderr")
	require.NoError(t, err)
	for i :=0; i<100; i++ {
		t.Run(fmt.Sprintf("take %d", i), func(t *testing.T) {
			stdout := bytes.Buffer{}
			stderr := bytes.Buffer{}
			err := runTerragruntCommand(
				t,
				fmt.Sprintf("terragrunt plan-all --terragrunt-non-interactive --terragrunt-working-dir %s", rootPath),
				&stdout,
				&stderr,
			)
			logBufferContentsLineByLine(t, stdout, "stdout")
			logBufferContentsLineByLine(t, stderr, "stderr")
			require.NoError(t, err)
		})
	}
}
```

The test output for the failed cases looks like:
```
            	            	Encountered the following errors:
            	            	open /var/folders/cf/nhvbzztn3yn08kfswy1rqkmh0000gn/T/terragrunt-test981814188/fixture-get-output/localstate/live/parent/.terragrunt-cache/yZpa9oXGPFA9yBeYJLKvMDWHQLA/nOHeCNZgRObX4kF5VK1jboCrx_w/.terragrunt-module-manifest: no such file or directory
```

We downgraded to 0.19.24 where it appears to be stable. 
Would it be possible to have a look and understand where the race condition is coming from, please?

**Comment by brikis98** [comment] 2019-10-11 08:05
@ekini Do you have any idea what could be causing this?

**Comment by ekini** [comment] 2019-10-11 10:33
I haven't been able to reproduce it so far. Will try to investigate more tomorrow.

**Comment by rmitula** [comment] 2019-10-15 05:57
I'm having the same problem as @dvulpe said, and on version **0.19.24** everything seems to work fine.

Example error output at the end of terragrunt **plan-all** command using 0.20.4 version:
```
[terragrunt] 2019/10/15 07:42:32 Encountered the following errors:
Hit multiple errors:
error downloading 'file:///Users/rmitula/Desktop/Company/infrastructure/terraform': open /Users/rmitula/Desktop/Company/infrastructure/live/global/dev/.terragrunt-cache/XM0YtL2xdz7j-Sq9CHfbzNBuR90/rXfWpL2tPlCaJpLebr06_0ly1Lg/global/modules/generic-config/files/.terragrunt-source-manifest: no such file or directory
Hit multiple errors:
error downloading 'file:///Users/rmitula/Desktop/Company/infrastructure/terraform': open /Users/rmitula/Desktop/Company/infrastructure/live/global/dev/.terragrunt-cache/XM0YtL2xdz7j-Sq9CHfbzNBuR90/rXfWpL2tPlCaJpLebr06_0ly1Lg/data-providers/provider3/modules/process-1/files/.terragrunt-source-manifest: no such file or directory
[terragrunt] 2019/10/15 07:42:32 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by ekini** [comment] 2019-10-15 07:30
The commits in question must be here https://github.com/gruntwork-io/terragrunt/pull/866 as it's the only difference between 0.19.24 and 0.19.25.

However, I don't see anything wrong with it.

I still can't reproduce the issue. I've tried:
1. Fresh repo on Mac with the test `TestDependencyPlanAllFlake`. Even with 500 passes it succeeds.
2. Fresh repo in Docker. Also no issues.
I used Terraform v0.12.10 and 0.12.7.

**Comment by podon** [comment] 2019-10-24 01:02
Noticing the same issue. It's really intermittent 

terragrunt version v0.20.4
Terraform v0.12.12
OSX + Ubuntu

``
[terragrunt] 2019/10/24 11:55:13 Encountered the following errors:
open /Users/peter.odonovan/projects/xxxxxxxx/deploy/xxxxxxx/vpc/.terragrunt-cache/eBDA0HQj6jnPLe2W4IcRuLq4eII/SmNP8PUyhYl3r9vRGSS8PFqGa5I/ci-runner.tf: no such file or directory
[terragrunt] 2019/10/24 11:55:13 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by dvulpe** [comment] 2019-10-30 07:16
Hi @yorinasub17 

I'll give the alpha version a go this week and let you know how it goes.

Thanks,
Dan

**Comment by yorinasub17** [comment] 2019-10-30 22:04
@dvulpe thanks! I would also appreciate it if you can give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.21.2-alpha.2 (https://github.com/gruntwork-io/terragrunt/pull/937) a try as well. Unlike the previous fix which rolls back the change, this will do proper synchronization of the `terragrunt output` call (and cache the results) so that we can keep the original change that is causing problems. If this works, we will most likely go with this version of the fix.

**Comment by geota** [comment] 2019-10-31 06:05
@yorinasub17 ive been having flaky *-all that seemed to be around having multiple modules depending on the same module (they all need to read its outputs). I have no idea if it's related to this issue, but I tested the latest alpha and so far the flakiness seems to be resolved.

**Comment by geota** [comment] 2019-10-31 18:36
this also resolved flaky in our gitlab CI/CD pipeline

example error from our terragrunt demo project pipeline:

```
[terragrunt] 2019/10/31 18:06:13 Encountered the following errors:
open /builds/heb-engineering/projects/heb-eng-sandbox/heb-ecom-sbxdemo/heb-ecom-sbxdemo-terraform/accounts/heb-ecom-sbxdemo-alpha/environments/bld/account-bootstrap/gitlab/group/.terragrunt-cache/FY9QfprjjTbanXO3jXY6Y6yNypU/Pr91Q2cIsjPsXNWIjAHf_EvC9aQ/outputs.tf: no such file or directory
[terragrunt] 2019/10/31 18:06:13 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
ERROR: Job failed: exit code 1
```

**Comment by yorinasub17** [comment] 2019-11-01 21:29
Released the latest alpha fix as `v0.21.2` (https://github.com/gruntwork-io/terragrunt/releases/tag/v0.21.2). Binaries will show up shortly. The original alpha releases will be deleted once the binaries for `v0.21.2` show up.

I will keep this open until I have confirmation that this fixes the root issue.

**Comment by dvulpe** [comment] 2019-11-02 13:55
Great work! 

I can confirm the latest release `v0.21.2` completely solves the flakiness we were experiencing with `plan-all`.

Thank you so much for fixing it!

**Comment by yorinasub17** [comment] 2019-11-04 21:15
Thanks for confirming! Will close this out.

**Closed by yorinasub17** 2019-11-04 21:15 UTC
Labels: bug, help wanted
