### ISSUE TITLE
Terragrunt state pull race condition

### ISSUE THREAD

**Issue by enarmontas** [gruntwork-io/terragrunt#1911] opened 2021-11-10 17:43 UTC
I am trying to pull Terragrunt state with this command. I need to define `--terragrunt-working-dir` as I am running the task from my root directory and I want to pull the state next to each `terragrunt.hcl`
```
terragrunt state pull \
  --terragrunt-working-dir aws/staging/iam-account/staging > aws/staging/iam-account/staging/terraform.tfstate
```
and I get the following error:
```
ERRO[0002] unexpected end of JSON input
ERRO[0002] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
However, if I use different name than `terraform.tfstate`, the command succeeds:
```
terragrunt state pull \
  --terragrunt-working-dir aws/staging/iam-account/staging > aws/staging/iam-account/staging/test.tfstate
```
```
cat aws/staging/iam-account/staging/test.tfstate
{
  "version": 4,
  "terraform_version": "1.0.5",
  ...
}
```
Versions:
```
$ terragrunt --version
terragrunt version v0.31.8

$ terraform --version
Terraform v1.0.5
on linux_amd64
```
I assume there is some sort of race condition specific to Terragrunt. When I run this command, empty file `terraform.tfstate` is created and Terraform fails the run, because state file JSON is invalid.

**Comment by yorinasub17** [comment] 2021-11-12 17:07
Closing as duplicate of #514. As mentioned there, the main issue is that `>` immediately creates an empty file at that location, before it starts `terragrunt` and thus leads to Terragrunt seeing an empty state file. We can probably do something to improve Terragrunt's handling of this situation, but the workaround for now is to use a different name other than `terraform.tfstate`.

**Closed by yorinasub17** 2021-11-12 17:07 UTC
