### ISSUE TITLE
Support using S3 for locks

### ISSUE THREAD

**Issue by bndw** [gruntwork-io/terragrunt#155] opened 2017-03-14 22:47 UTC
Is it possible to store the lock along side the state in an S3 bucket? Are there any technical limitations?

**Comment by josh-padnick** [comment] 2017-03-14 23:01
The problem is that S3 is eventually consistent. Suppose Terragrunt User A writes the lock into S3 and that Terragrunt User B reads the lock a second later. S3 does not guarantee he'll actually see this value.

I'm going to close this comment but if you have any other questions, feel free to ask!

**Closed by josh-padnick** 2017-03-14 23:01 UTC
