### ISSUE TITLE
Terragrunt fail with There is no variable named "dependency" error

### ISSUE THREAD

**Issue by askoriy** [gruntwork-io/terragrunt#1257] opened 2020-07-21 13:15 UTC
When using dependency variables in hooks, command `terragrunt plan` finish successfully,
but `terragrunt plan-all` fails with error:
```
[terragrunt] 2020/07/21 16:09:07 Error processing module at '/home/askoriy/tg-test/child/terragrunt.hcl'. How this module was found: Terragrunt config file found in a subdirectory of /home/askoriy/tg-test. Underlying error: /home/askoriy/tg-test/child/terragrunt.hcl:6,56-66: Unknown variable; There is no variable named "dependency"., and 1 other diagnostic(s)

```

Terragrunt version: v0.23.31

Steps to reproduce:
1. Create folders structure:

```
# terragrunt.hcl
terraform {}

# main.tf
resource "null_resource" "null1" {}

output testoutput {
  value = "test123"
}

# child/terragrunt.hcl
terraform {
  source = "."

  before_hook "before_hook1" {
    commands = ["apply", "plan"]
    execute  = ["sh", "-c", "echo Dependency output: ${dependency.parent.outputs.testoutput}"]
  }
}

dependency "parent" {
  config_path  = "../"
  mock_outputs = {
    testoutput = "mock"
  }
}

# child/main.tf 
resource "null_resource" "null2" {}

```
2. run `terragrunt plan` from `child` directory to see that no errors with plan command
3. run `terragrunt plan-all` from `child` directory and see error described in the issue.

**Comment by askoriy** [comment] 2020-07-21 13:30
seems duplicate https://github.com/gruntwork-io/terragrunt/issues/1226

**Comment by yorinasub17** [comment] 2020-07-21 16:08
Closing as duplicate of https://github.com/gruntwork-io/terragrunt/issues/992 . Please follow that ticket to be notified when we implement this.

See [the parsing order docs](https://terragrunt.gruntwork.io/docs/getting-started/configuration/#configuration-parsing-order) to understand why you can't do this.

**Closed by yorinasub17** 2020-07-21 16:08 UTC
