### ISSUE TITLE
value not known

### ISSUE THREAD

**Issue by rgarrigue** [gruntwork-io/terragrunt#1158] opened 2020-04-29 06:01 UTC
HI there

I c/c'ed my terraform and simplified it for a client, and trying to `terragrunt plan`, I've a barren `value not known`. Can you give me a lead ?

```
~/work/client/terraform/production/aws/us-east-1/key_pair ᐅ terragrunt plan               
[terragrunt] 2020/04/29 07:43:14 Reading Terragrunt config file at /home/remy/work/client/terraform/production/aws/us-east-1/key_pair/terragrunt.hcl
[terragrunt] 2020/04/29 07:43:14 value is not known
[terragrunt] 2020/04/29 07:43:14 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

I've checked everything I could, everything seems valid. terragrunt version v0.23.12 & Terraform v0.12.24.

**Comment by rgarrigue** [comment] 2020-04-29 06:07
Ok, found the reason : the terragrunt.hcl included a 

```
inputs = merge(
  yamldecode(file("${find_in_parent_folders("secrets.yaml")}")),
  yamldecode(file("${find_in_parent_folders("global.yaml")}")),
  yamldecode(file("${find_in_parent_folders("environment.yaml")}")),
  # yamldecode(file("${find_in_parent_folders("provider.yaml")}")),
  yamldecode(file("${find_in_parent_folders("region.yaml")}"))
)
```

The secrets.yaml file was empty of value, with just a `---` : I didn't needed it for the simplified terraform for this client, but wanted to keep it there as a reminder that secrets should go there.

You might want to add a more explicit message ?

**Comment by yorinasub17** [comment] 2020-04-29 14:49
I believe this error message is coming from `yamldecode`. With that said, `terragrunt` should be outputing line numbers for it's error messages (which it currently isn't because we aren't using `diag` everywhere).

A PR to enhance that would be great, if not we will try to get to this when we have spare cycles.

**Comment by levkohimins** [comment] 2023-09-19 18:20
Hi @rgarrigue,
I tried your example to reproduce the issue, but I didn't manage, I didn't get any errors. Looks like this has already been fixed. Therefore I am closing this question.

**Closed by levkohimins** 2023-09-19 18:20 UTC
Labels: bug
