### ISSUE TITLE
Terragrunt needs a logo!

### ISSUE THREAD

**Issue by skyzyx** [gruntwork-io/terragrunt#1152] opened 2020-04-24 21:10 UTC
Terraform has that cubic "T" thing. https://www.terraform.io/assets/files/press-kit.zip

Indicators of a good logo include working in a variety of places:

* With color
* Without color (monochromatic)
* Scales up well (1024x1024)
* Scales down well (16x16)

I suppose I could use the Gruntwork favicon dude in the interim for some in-house documentation I'm writing for people who are new to both Terraform + Terragrunt, but it would be nice for Terragrunt to have its own visual identity so that people who are new to both tools can tell both _terra_'s apart from each other better.

**Comment by brikis98** [comment] 2020-04-27 08:30
Thx for filing. Closing as duplicate of #570.

**Closed by brikis98** 2020-04-27 08:30 UTC
