### ISSUE TITLE
Random "no suitable version installed"

### ISSUE THREAD

**Issue by thnee** [gruntwork-io/terragrunt#289] opened 2017-09-08 14:40 UTC
Sometimes, seemingly at random, when doing commands like `terragrunt apply --terragrunt-source=../../../modules//module`, providers become unavailable with output like this:

```
[terragrunt] 2017/09/08 16:37:29 Backend s3 has not changed.
[terragrunt] 2017/09/08 16:37:29 Running command: terraform apply
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.aws: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".

error satisfying plugin requirements
[terragrunt] 2017/09/08 16:37:35 exit status 1
```

I usually just `rm -rf /tmp/terragrunt/` and it starts working again.

**Comment by brikis98** [comment] 2017-09-08 14:54
Thanks for reporting. I believe this is caused by the same thing as #266: the OS deleting files in the tmp folder, but not the folders, fooling Terragrunt's caching check. Should be an easy fix is anyone is up for a quick PR :)

**Comment by brikis98** [comment] 2017-09-29 20:01
Closing as duplicate of #266. Hopefully #301 will fix this.

**Closed by brikis98** 2017-09-29 20:01 UTC
Labels: bug, help wanted

**Comment by 321kranthikumar** [comment] 2017-12-20 02:42
Does this Issue fixed Sir ?

**Comment by brikis98** [comment] 2017-12-20 02:52
It's fixed in most cases, but not all. See https://github.com/gruntwork-io/terragrunt/issues/388 for a potentially more permanent fix.

**Comment by 321kranthikumar** [comment] 2017-12-20 02:58
Thanks for replying 
 
 
--------- Original Message --------- Subject: Re: [gruntwork-io/terragrunt] Random "no suitable version installed" (#289)
