### ISSUE TITLE
Provider Caching not working as expected, still seeing multiple same version providers, disk usage is still the same.

### ISSUE THREAD

**Issue by nsb413** [gruntwork-io/terragrunt#3090] opened 2024-04-23 13:23 UTC
**Describe the bug**
Provider Caching not working as expected, still seeing multiple same version providers, disk usage is still the same. Was pointed to provider-cache as solution [here](https://github.com/gruntwork-io/terragrunt/issues/561)

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```
export TERRAGRUNT_DOWNLOAD="C:\temp\terragrunt"
terragrunt run-all plan --terragrunt-provider-cache --terragrunt-provider-cache-dir c:\temp\terragrunt\provider-cache
....
time=2024-04-23T08:12:28-05:00 level=info msg=Shutting down Terragrunt Cache server...
time=2024-04-23T08:12:28-05:00 level=info msg=Terragrunt Cache server stopped
```

**Expected behavior**

Expected behavior is, there should be only one copy for each  aws terraform provider version. 
I have 5 modules in my project, I see 5 folders in C:\temp\terragrunt, in each folder i am seeing the aws terraform provider (~430MB), the size of TERRAGRUNT_DOWNLOAD is now ~2.12 GB, I was thinking using "Provider Caching" feature would reduce the disk usage.
However, i am seeing a cache folder created in project root
```
TEMPTERRAGRUNTPROVIDER-CACHE
└───registry.terraform.io
    └───hashicorp
        └───aws
            ├───5.45.0
            │   └───windows_amd64
            └───5.46.0
                └───windows_amd64
```

**Nice to have**
- [x] Terminal output
- [x] Screenshots
<img width="1512" alt="image" src="https://github.com/gruntwork-io/terragrunt/assets/89711679/a546387d-08b9-43a7-8fdc-c7f6c3a05102">
<img width="828" alt="image" src="https://github.com/gruntwork-io/terragrunt/assets/89711679/6e0893b9-ebf7-4db8-82c6-0f4b6f7474cc">

**Versions**
- Terragrunt version: v0.57.6
- Terraform version: Terraform v1.7.5 on windows_386
- Environment details (Ubuntu 20.04, Windows 10, etc.): Windows 10 Enterprise

**Additional context**

**Comment by levkohimins** [comment] 2024-04-24 14:41
Hi @nsb413, 
I didn't see the `c:\temp\terragrunt\provider-cache` directory in your screenshot, which means something went wrong. Please run this command with `--terragrunt-log-level debug` and provide the full log here.

**Comment by levkohimins** [comment] 2024-04-24 15:30
Update: Similar [issue](https://github.com/gruntwork-io/terragrunt/issues/3076#issuecomment-2075217119). Please follow the updates there.

**Comment by nsb413** [comment] 2024-04-24 17:11
```
TERRAGRUNT_DOWNLOAD=c:/temp/.terragrunt-cache
terragrunt run-all plan --terragrunt-provider-cache --terragrunt-log-level debug
```

Output
```
....
time=2024-04-24T12:05:10-05:00 level=debug msg=Caching terraform providers for "c:/temp/.terragrunt-cache/hwNqL6ri8wLIL3D5KSJ45uqYTfA/ajGUGXi9iD1dMESWCbw4_fg6IEA/glue/glue-job"
....
```
I think it is not using the default provider location (`%LocalAppData%\terragrunt\providers` on Windows), but instead trying to use TERRAGRUNT_DOWNLOAD path for caching. 

```
$ terragrunt -v
terragrunt version v0.57.6

$ terraform -v
Terraform v1.8.1
on windows_386
```

**Comment by levkohimins** [comment] 2024-04-30 17:44
Hi @nsb413, could you please confirm that the issue is resolved?

**Comment by levkohimins** [comment] 2024-05-07 18:28
I'm closing the issue since it seems to be resolved. Feel free to reopen if this is not the case.

**Closed by levkohimins** 2024-05-07 18:28 UTC
Labels: bug, terragrunt
