### ISSUE TITLE
Unexpected behavior picking a terragrunt.hcl file

### ISSUE THREAD

**Issue by steeling** [gruntwork-io/terragrunt#1368] opened 2020-09-23 04:19 UTC
Hi,

I see the description here about the precedence for finding the terragrunt.hcl file https://terragrunt.gruntwork.io/docs/getting-started/configuration/#terragrunt-configuration-file. 

With the following setup

```
terragrunt-project 
  - enviroment
     - dev
        - terragrunt.hcl
        - main.tf 
     - prod
        - terragrunt.hcl
     - terragrunt.hcl
  - module
     - mod1
        - main.tf
        - outputs.tf
        - variables.tf
```

I'm attempting to set `inputs` so I can set shared vars at each level of the environments. According to this https://github.com/gruntwork-io/terragrunt/issues/1011 I should be able to do this automatically, but I'm running into issues based on which dir I run `terragrunt plan` from. Do I really have to run `terragrunt <cmd>` from the correct dir for this to work? How does this not provide a surface for users to shoot themselves in the foot?

**Comment by steeling** [comment] 2020-09-23 04:28
err... i think i'm doing things wrong. Apologies for the noise. My issue is that I thought I could specify the module as an arg (not a flag), and my dir setup was such that it wasn't throwing errors

**Comment by steeling** [comment] 2020-09-23 04:46
Actually, this might be worth reopening (or duping against https://github.com/gruntwork-io/terragrunt/issues/315). I'll reopen and let y'all pick which :)

**Comment by brikis98** [comment] 2020-09-24 09:16
Closing as dupe of #315, as there's already some discussion there.

**Closed by brikis98** 2020-09-24 09:16 UTC
