### ISSUE TITLE
Ways to ignore output for plan -detailed-exitcode?

### ISSUE THREAD

**Issue by AnthonyWC** [gruntwork-io/terragrunt#1680] opened 2021-05-20 16:21 UTC
Currently if I have output that changes, then if I use `plan -detailed-exitcode` it will fail (output with 2).

Is there any way to get around this?  Perhaps as an extra option to suppress/ignore output.

**Comment by yorinasub17** [comment] 2021-05-24 14:48
This is actually expected behavior of `detailed-exitcode`. Output changes are now tracked in the plan since `0.13.0`:

> cli: The terraform plan and terraform apply commands now recognize changes to root module outputs as side-effects to be approved and applied. This means you can apply root module output changes using the normal plan and apply workflow. (#25047)

[source](https://github.com/hashicorp/terraform/blob/v0.13/CHANGELOG.md)

As such, this would be considered a `diff` by the `-detailed-exitcode` option and thus is returning 2.

FWIW, there is [this open ticket](https://github.com/hashicorp/terraform/issues/25739) to suggest an additional exit code for create only plans. Perhaps that might address your use case?

---

Will be closing this since this is a terraform issue instead of terragrunt.

**Closed by yorinasub17** 2021-05-24 14:48 UTC
Labels: question
