### ISSUE TITLE
Error parsing Terragrunt config file .terragrunt: state_file_id cannot be empty

### ISSUE THREAD

**Issue by mcraig88** [gruntwork-io/terragrunt#47] opened 2016-11-04 21:44 UTC
Trying to set up terragrunt for the first time using this command:
terragrunt plan --var-file=..\terraform.tfvars -out .\plan.out -var "username=$env:username"

and I get:
Error parsing Terragrunt config file .terragrunt: state_file_id cannot be empty

.terragrunt file contents:
```
# Configure Terragrunt to use DynamoDB for locking
lock = {
	backend = "dynamodb"
	config {
		stateFileId = "my-apps"
		awsRegion = "us-west-2"
		tableName = "terragrunt_locks"
		maxLockRetries = 360
	}
}

# Configure Terragrunt to automatically store tfstate files in an S3 bucket
remoteState = {
  backend = "s3"
  backendConfigs = {
    encrypt = "true"
    bucket = "tfremotestate"
    key = "terraform.tfstate"
    region = "us-west-2"
  }
}
```

There is an S3 bucket created, called tfremotestate, and I have full Admin rights.

**Comment by josh-padnick** [comment] 2016-11-04 21:52
In #33, we changed all config values to use snake_case, not CamelCase. Can you change `stateFileId` to `state_file_id` as well as the other values to match snake_case and see if that fixes your issue?

**Comment by mcraig88** [comment] 2016-11-04 21:58
Thanks, I have updated as below:

# Configure Terragrunt to use DynamoDB for locking
lock = {
backend = "dynamodb"
config {
state_file_id = "my-apps"
aws_region = "us-west-2"
table_name = "terragrunt_locks"
max_lock_retries = 360
}
}

# Configure Terragrunt to automatically store tfstate files in an S3 bucket
remoteState = {
  backend = "s3"
  backendConfigs = {
    encrypt = "true"
    bucket = "tfremotestate"
    key = "terraform.tfstate"
    region = "us-west-2"
  }
}

output:

[terragrunt] 2016/11/04 14:54:56 Attempting to acquire lock for state file
my-apps in DynamoDB
[terragrunt] 2016/11/04 14:54:57 Lock table terragrunt_locks does not exist
in DynamoDB. Will need to create it just this first time.
[terragrunt] 2016/11/04 14:54:57 Creating table terragrunt_locks in DynamoDB
[terragrunt] 2016/11/04 14:54:57 Table terragrunt_locks is not yet in
active state. Will check again after 10s.
[terragrunt] 2016/11/04 14:55:07 Success! Table terragrunt_locks is now in
active state.
[terragrunt] 2016/11/04 14:55:07 Attempting to create lock item for state
file my-apps in DynamoDB table terragrunt_locks
[terragrunt] 2016/11/04 14:55:07 Lock acquired!
[terragrunt] 2016/11/04 14:55:07 Running command: terraform apply .\plan.out


However, remote state does not get created, does it matter that I have
state local in my folder? Should I uplode my current terraform.state to s3
and remove the local copy?

**Comment by josh-padnick** [comment] 2016-11-04 22:05
> However, remote state does not get created. 

I'm guessing the issue is that your `.terraform/` folder contains a previous terraform state configuration, and terragrunt does not yet overwrite an existing terraform state configuration. You can solve this as follows:

1. Ideally, `terraform destroy` everything so you can start from a clean slate. If that's not possible manually upload your state to the S3 location. To be safe, ensure S3 bucket versioning is enabled, and consider taking one more backup.

2. Now `rm -Rf .terraform`

3. Now run `terragrunt apply` again. 

> Does it matter that I have state local in my folder? 

I believe Terraform will keep a copy of your terraform state locally, even if you have remote state enabled. But if you're referring to your state configuration (which is local by default), then, yes, I believe that was the issue here.

> Should I upload my current terraform.state to s3 and remove the local copy?

Exactly what I just suggested so we're thinking in line with each other!

**Comment by mcraig88** [comment] 2016-11-07 19:49
I uploaded state to S3, and removed the local copy. (It wants to do a full
create on everything)
I replaced the local state file, made a minor change, and ran terragrunt
plan/apply, but remote state file did not get updated.
I there any enhanced logging I can enable to further troubleshoot?

I'd be happy to do a screen share and walk through.

**Comment by mcraig88** [comment] 2016-11-07 23:05
FYI, I was able to create remote state using the following command (note, I'm running on Windows 10, in Powershell)

terraform remote config -backend=s3 -backend-config="bucket=tfremotestate-gcotech" -backend-config="key=terraform-state-us-west-2-lab/terraform.tfstate" -backend-config="region=us-west-2"

Not sure why terragrunt didn't do this for me?

**Comment by brikis98** [comment] 2016-11-08 22:17
The most recent `.terragrunt` you posted is still using camelCase for the `remoteState` settings. As mentioned above, and documented in the [Readme](https://github.com/gruntwork-io/terragrunt#quick-start), all the config settings now use snake_case.

**Comment by mcraig88** [comment] 2016-11-08 22:51
```
# Configure Terragrunt to use DynamoDB for locking
lock = {
	backend = "dynamodb"
	config {
		state_file_id = "my-apps"
		aws_region = "us-west-2"
		table_name = "terragrunt_locks"
		max_lock_retries = 360
	}
}

# Configure Terragrunt to automatically store tfstate files in an S3 bucket
remoteState = {
  backend = "s3"
  backendConfigs = {
    encrypt = "false"
    bucket = "tfremotestate"
    key = "terraform-state-us-west-2-lab/terraform.tfstate"
    region = "us-west-2"
  }
}


```

**Comment by brikis98** [comment] 2016-11-08 22:53
Your `remoteState` is still camelCase :) It should look more like this:

```hcl
remote_state = {
  backend = "s3"
  config = {
    encrypt = "false"
    bucket = "tfremotestate"
    key = "terraform-state-us-west-2-lab/terraform.tfstate"
    region = "us-west-2"
  }
}
```

**Comment by mcraig88** [comment] 2016-11-08 22:54
geek fail. thanks I'll try it.

**Comment by brikis98** [comment] 2016-11-15 14:33
@mcraig88 Hopefully things are working for you now. I'm going to close this issue.

**Closed by brikis98** 2016-11-15 14:33 UTC

**Comment by mcraig88** [comment] 2016-11-15 16:21
Yes, thank you, I was able to get this working. and Thank you very much for
your quick email support!!
