### ISSUE TITLE
terragrunt not creating the s3 bucket

### ISSUE THREAD

**Issue by madhuryg** [gruntwork-io/terragrunt#1370] opened 2020-09-24 04:32 UTC
terraform version 0.13.3
terragrunt version v0.23.40
Not creating the s3 bucket by default if not found..
[terragrunt] [C:\Users\Madhuri.Gattupalli\projects\aurora\AWSDevOps\Terragrunt\qa\postgres-parameter-group-12] 2020/09/24 00:31:51 Initializing remote state for the s3 backend
[terragrunt] [C:\Users\Madhuri.Gattupalli\projects\aurora\AWSDevOps\Terragrunt\qa\postgres-parameter-group-12] 2020/09/24 00:31:51 [terragrunt] [C:\Users\Madhuri.Gattupalli\projects\aurora\AWSDevOps\Terragrunt\qa\postgres-parameter-group-12]  Remote state S3 bucket inovalon.qsixl.analytics.terraform-backend.qa does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)

[terragrunt] 2020/09/24 00:31:51
[terragrunt] 2020/09/24 00:31:51 Encountered the following errors:
NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: 3D6539020EF9EE1F, host id: kNaqX/XiD7t+MpD+jydwxnwtDoI6vyCixuf3LSJoJYWSfYUhF14DquP0ZBW3KHN1FjsJpr9uBLY=
Cannot process module Module C:/Users/Madhuri.Gattupalli/projects/aurora/AWSDevOps/Terragrunt/qa/postgres-rds-aurora2 (excluded: false, dependencies: [C:/Users/Madhuri.Gattupalli/projects/aurora/AWSDevOps/Terragrunt/qa/postgres-parameter-group-12]) because one of its dependencies, Module C:/Users/Madhuri.Gattupalli/projects/aurora/AWSDevOps/Terragrunt/qa/postgres-parameter-group-12 (excluded: false, dependencies: []), finished with an error: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: 3D6539020EF9EE1F, host id: kNaqX/XiD7t+MpD+jydwxnwtDoI6vyCixuf3LSJoJYWSfYUhF14DquP0ZBW3KHN1FjsJpr9uBLY=
[terragrunt] 2020/09/24 00:31:51 Unable to determine underlying exit code, so Terragrunt will exit with error code 1

**Comment by brikis98** [comment] 2020-09-25 07:34
Did you enter `y`? 

Is it possible the bucket exists already in some AWS account, but you're authenticated to a different account?

**Comment by ChristophShyper** [comment] 2020-09-28 09:22
> Is it possible the bucket exists already in some AWS account, but you're authenticated to a different account?

Exactly. This error is typically caused by wrong credentials.

Also use Terragrunt 0.25 for Terraform 0.13.

**Comment by madhuryg** [comment] 2020-09-28 22:12
thank u ... s3 was not existing .... let me upgrade the version

**Comment by brikis98** [comment] 2021-01-18 10:16
Sounds like a creds or usage error, and no follow up in a few months, so closing.

**Closed by brikis98** 2021-01-18 10:16 UTC
Labels: question
