### ISSUE TITLE
Add a --quiet flag to suppress terragrunt-related output

### ISSUE THREAD

**Issue by ldormoy** [gruntwork-io/terragrunt#576] opened 2018-09-27 12:19 UTC
The CLI output is quite chatty, which is very nice but in some cases annoying.

Example: using atlantis to generate plan and apply outputs as GitHub PR comments, it creates very long comments that sometimes even have to be splitted by GitHub.

An idea would be to optionally disable the terragrunt output, using a `--quiet` flag, for instance. This would suppress the `[terragrunt]` prefixed lines and keep only the terraform output.

For the record, the corresponding terraform issue: https://github.com/hashicorp/terraform/issues/10507

**Comment by brikis98** [comment] 2018-09-27 15:38
Duplicate of #432. PRs welcome!

**Closed by brikis98** 2018-09-27 15:38 UTC
