### ISSUE TITLE
Error "There is no variable named 'dependency'.

### ISSUE THREAD

**Issue by lpossamai** [gruntwork-io/terragrunt#2956] opened 2024-02-21 21:54 UTC
## Description

I'm getting the following error when trying to `plan` or `apply` changes with Terragrunt:
```
❯ make init
cd . && terragrunt init
ERRO[0001] Error: Unknown variable

ERRO[0001]   on /Users/lucas/MEGAsync/Documents/work/git/mycompany/mycompany-infrastructure/environments/prod/ap-southeast-2/sms-usage-uploader-lambda/terragrunt.hcl line 118:
ERRO[0001]  118:   kms_key_arn = dependency.kms.outputs.key_arn
ERRO[0001]
ERRO[0001] There is no variable named "dependency".

ERRO[0001] Error: Unknown variable

ERRO[0001]   on /Users/lucas/MEGAsync/Documents/work/git/mycompany/mycompany-infrastructure/environments/prod/ap-southeast-2/sms-usage-uploader-lambda/terragrunt.hcl line 127:
ERRO[0001]  127:   vpc_subnet_ids         = dependency.vpc.outputs.private_subnets
ERRO[0001]
ERRO[0001] There is no variable named "dependency".

ERRO[0001] Error: Unknown variable

ERRO[0001]   on /Users/lucas/MEGAsync/Documents/work/git/mycompany/mycompany-infrastructure/environments/prod/ap-southeast-2/sms-usage-uploader-lambda/terragrunt.hcl line 128:
ERRO[0001]  128:   vpc_security_group_ids = [dependency.vpc.outputs.default_security_group_id]
ERRO[0001]
ERRO[0001] There is no variable named "dependency".

ERRO[0001] Error: Unknown variable

ERRO[0001]   on /Users/lucas/MEGAsync/Documents/work/git/mycompany/mycompany-infrastructure/environments/prod/ap-southeast-2/sms-usage-uploader-lambda/terragrunt.hcl line 150:
ERRO[0001]  150:         for arn in concat(dependency.ssm.outputs.ssm_parameters_with_ignore_changes_arn, dependency.ssm.outputs.ssm_parameters_without_ignore_changes_arn) : arn
ERRO[0001]
ERRO[0001] There is no variable named "dependency".

ERRO[0001] Error: Unknown variable

ERRO[0001]   on /Users/lucas/MEGAsync/Documents/work/git/mycompany/mycompany-infrastructure/environments/prod/ap-southeast-2/sms-usage-uploader-lambda/terragrunt.hcl line 150:
ERRO[0001]  150:         for arn in concat(dependency.ssm.outputs.ssm_parameters_with_ignore_changes_arn, dependency.ssm.outputs.ssm_parameters_without_ignore_changes_arn) : arn
ERRO[0001]
ERRO[0001] There is no variable named "dependency".

WARN[0001] Error reading partial config  for dependency lambda: /Users/lucas/MEGAsync/Documents/work/git/mycompany/mycompany-infrastructure/environments/prod/ap-southeast-2/sms-usage-uploader-lambda/terragrunt.hcl:118,17-27: Unknown variable; There is no variable named "dependency"., and 4 other diagnostic(s)
INFO[0011] Downloading Terraform configurations from tfr:///terraform-aws-modules/eventbridge/aws?version=3.2.2 into /Users/lucas/MEGAsync/Documents/work/git/mycompany/mycompany-infrastructure/environments/prod/ap-southeast-2/sms-usage-uploader-scheduler/.terragrunt-cache/x1f6kqkMHJdRAwLRHsowDcrH5oQ/mD5dBOZbTj-YOZPbE56PudA-IQs

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 5.27.0"...
- Installing hashicorp/aws v5.37.0...
- Installed hashicorp/aws v5.37.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

I've tried the following:

1. Removed `.terraform.lock.hcl` and `.terragrunt-cache`
2. Ran `terragrunt init -upgrade`

## Versions

- Module version [Required]: `3.2.2`

- Terraform version: `v1.7.4` on `on darwin_arm64`
- Terragrunt version: `0.55.4`
- Provider version(s): `aws v5.37.0`

## Reproduction Code [Required]

I've tried the following:

1. Removed `.terraform.lock.hcl` and `.terragrunt-cache`
2. Ran `terragrunt init -upgrade`
3. Ran `terragrunt providers lock -platform=darwin_amd64 -platform=windows_amd64 -platform=linux_amd64 -platform=darwin_arm64 -platform=linux_arm64 -platform=darwin_arm64`

`environments/prod/ap-southeast-2/sms-usage-uploader-scheduler`:
```HCL
# ---------------------------------------------------------------------------------------------------------------------
# TERRAGRUNT CONFIGURATION
# This is the configuration for Terragrunt, a thin wrapper for Terraform that helps keep your code DRY and
# maintainable: https://github.com/gruntwork-io/terragrunt
# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
# Locals are named constants that are reusable within the configuration.
# ---------------------------------------------------------------------------------------------------------------------
locals {
  # Automatically load environment-level variables
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  # Automatically load region-level variables
  region_vars = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  aws_region  = local.region_vars.locals.aws_region

  # Extract out common variables for reuse
  env        = local.environment_vars.locals.environment
  account_id = local.environment_vars.locals.aws_account_id

  # create a list of subnets
  private_subnets_cidr     = tolist(concat([local.environment_vars.locals.private_subnet_a, local.environment_vars.locals.private_subnet_b, local.environment_vars.locals.private_subnet_c]))
  public_subnets_cidr      = concat([local.environment_vars.locals.public_subnet_a, local.environment_vars.locals.public_subnet_b, local.environment_vars.locals.public_subnet_c])
  database_subnets_cidr    = concat([local.environment_vars.locals.database_subnet_a, local.environment_vars.locals.database_subnet_b, local.environment_vars.locals.database_subnet_c])
  elasticache_subnets_cidr = concat([local.environment_vars.locals.elasticache_subnet_a, local.environment_vars.locals.elasticache_subnet_b, local.environment_vars.locals.elasticache_subnet_c])
  infra_subnets_cidr       = concat([local.environment_vars.locals.infra_subnet_a, local.environment_vars.locals.infra_subnet_b, local.environment_vars.locals.infra_subnet_c])

  # Extract out workspace variables for reuse
  VPC_CIDR = local.environment_vars.locals.VPC_CIDR
}

# We override the terraform block source attribute here just for the QA environment to show how you would deploy a
# different version of the module in a specific environment.
# https://github.com/terraform-aws-modules/terraform-aws-eventbridge/releases
terraform {
  source = "${include.envcommon.locals.base_source_url}?version=3.2.2"
}

# ---------------------------------------------------------------------------------------------------------------------
# Include configurations that are common used across multiple environments.
# ---------------------------------------------------------------------------------------------------------------------

# Include the root `terragrunt.hcl` configuration. The root configuration contains settings that are common across all
# components and environments, such as how to configure remote state.
include "root" {
  path   = find_in_parent_folders()
  expose = true
}

# Include the envcommon configuration for the component. The envcommon configuration contains settings that are common
# for the component across all environments.
include "envcommon" {
  path   = "${dirname(find_in_parent_folders())}/config/_envcommon/eventbridge.hcl"
  expose = true
}

dependency "lambda" {
  config_path = "${dirname(find_in_parent_folders())}/environments/${local.env}/${local.aws_region}/sms-usage-uploader-lambda"

  # Configure mock outputs for the `validate` command that are returned when there are no outputs available (e.g the
  # module hasn't been applied yet.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]

  mock_outputs = {
    lambda_function_arn = "known-after-apply"
  }
}

# ---------------------------------------------------------------------------------------------------------------------
# MODULE PARAMETERS
# These are the variables we have to pass in to use the module. This defines the parameters that are common across all
# environments.
# ---------------------------------------------------------------------------------------------------------------------
inputs = {
  create = true
  # Remove the "-rule" postfix from the event rule name
  append_rule_postfix = false

  name        = "sms-usage-uploader-${local.env}"
  description = "Schedule the sms usage upload requested event"

  # Event bus is managed by another module
  create_bus = false

  attach_lambda_policy = true
  lambda_target_arns   = [dependency.lambda.outputs.lambda_function_arn]

  role_name = "sms-usage-uploader-${local.env}"

  rules = {
    SMSUsageUploadRequested = {
      schedule_expression = local.environment_vars.locals.sms_usage_uploader_scheduled_expression
      timezone            = "UTC"
      arn                 = dependency.lambda.outputs.lambda_function_arn
      event_pattern = jsonencode(
        {
          "detail-type" : [
            "SMSUsageUploadRequested"
          ]
        }
      )
      input = jsonencode({ "detail-type" : "SMSUsageUploadRequested" })
    }
    SMSUsageUploadStatusCheckRequested = {
      schedule_expression = local.environment_vars.locals.sms_usage_uploader_scheduled_expression
      timezone            = "UTC"
      arn                 = dependency.lambda.outputs.lambda_function_arn
      event_pattern = jsonencode(
        {
          "detail-type" : [
            "SMSUsageUploadStatusCheckRequested"
          ]
        }
      )
      input = jsonencode({ "detail-type" : "SMSUsageUploadStatusCheckRequested" })
    }
  }

  tags = local.environment_vars.locals.tags
}
```

Checking outputs in the `environments/prod/ap-southeast-2/sms-usage-uploader-lambda` directory returns successful data:

## Expected behavior

The module should plan the changes without any issues.

## Actual behavior

Instead, I get the error described in the beginning of this post.

**Comment by denis256** [comment] 2024-02-22 09:32
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/2955

**Closed by denis256** 2024-02-22 09:32 UTC
Labels: bug
