### ISSUE TITLE
Regenerated backend line order changes on each run

### ISSUE THREAD

**Issue by bondsbw** [gruntwork-io/terragrunt#1272] opened 2020-07-30 15:54 UTC
I use `overwrite_terragrunt` on my backend configurations:

```hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    ...
  }
}
```

Each time Terragrunt regenerates the `backend.tf` file, it generates the configuration lines in a different order.  Since I'm storing `backend.tf` in source control, this shows as a change each time.

**Comment by bondsbw** [comment] 2020-07-30 15:54
As for why I store `backend.tf` in source control, it allows members of my team to run Terraform without Terragrunt.

**Comment by yorinasub17** [comment] 2020-07-31 06:45
Closing as duplicate of #1102 , and there is a PR: https://github.com/gruntwork-io/terragrunt/pull/1165

Please follow those tickets to be notified when this will be fixed.

**Closed by yorinasub17** 2020-07-31 06:45 UTC
Labels: bug, good first issue, help wanted
