### ISSUE TITLE
passing outputs between modules only works from within module folders

### ISSUE THREAD

**Issue by imod** [gruntwork-io/terragrunt#1376] opened 2020-09-28 16:59 UTC
Hi,

I'm following the description given at for [passing outputs between modules](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules)...

Given the following example:

```
root
├─ terragrunt.hcl
├── backend-app
│   ├── main.tf
│   └── terragrunt.hcl
└── vpc
    ├── main.tf
    └── terragrunt.hcl
```

The `terragrunt.hcl` in the `root` folder only contains the `remote_state` configuration:
```
remote_state {
  backend = "azurerm"
  config = {
    resource_group_name  = "XXX"
    storage_account_name = "XXX"
    container_name       = "XXX"
    key                  = "${path_relative_to_include()}/terraform.tfstate"
  }
}
```

for `backend-app` I define a variable for `vpc_id` and the the following dependency:

```
include {
  path = find_in_parent_folders()
}
dependency "vpc" {
  config_path = "../vpc"
}
inputs = {
  vpc_id = dependency.vpc.outputs.vpc_id
}
```

Now I expected the following to work:

```
cd root
terragrunt apply vpc
terragrunt apply backend-app
```
...but I get a prompt asking me for the value of `vpc_id` (Note: I'm starting `terragrunt from within the root directory)

In my experience this only works when I do the following:

```
cd vpc
terragrunt apply
cd ../backend-app
terragrunt apply
```
Note: I'm always changing into the module folders and start terragrunt from there. 

Is this correct, is this expected or am I doing something wrong?

**Comment by imod** [comment] 2020-09-28 20:06
Here is an example project: https://github.com/imod/terragrunt-test

**Comment by yorinasub17** [comment] 2020-09-28 20:55
This looks like a duplicate of https://github.com/gruntwork-io/terragrunt/issues/315

The main issue is that terragrunt does not realize the `terragrunt.hcl` it should use is in the target directory you provided on the CLI, and not the one it finds in the current dir. You can either do:

```
(cd vpc && terragrunt apply)
terragrunt apply --terragrunt-working-dir ./vpc
```

**Comment by yorinasub17** [comment] 2020-09-28 20:56
Closing as dupe of #315 . Please follow/comment on that ticket if either workaround provided does not work for you.

**Closed by yorinasub17** 2020-09-28 20:56 UTC
