### ISSUE TITLE
Unnecessary terraform init when terragrunt.hcl includes dependencies?

### ISSUE THREAD

**Issue by maximivanov** [gruntwork-io/terragrunt#1450] opened 2020-12-01 00:10 UTC
First, thanks for Terragrunt! Coming from programming world, it's good to stay `DRY` while working with Terraform :)

I may be missing something but looks like there's an unnecessary call to `terraform init` every time I run `terragrunt plan` or `apply` from a module that has a dependency on another module.

A minimal reproducible example below.

**Context**

I'm on OS X 10.13.6

```bash
  ~ $ terraform --version
Terraform v0.13.5
  ~ $ terragrunt --version
terragrunt version v0.26.7
```

**Steps to reproduce**

1\. Clone https://github.com/maximivanov/reproduce-terragrunt-azure-extra-tf-init

2\. Create remote TF state storage

```bash
cd tf_backend/
terraform init
terraform apply
```

3\. Deploy parent module (Azure Resource Group) with Terragrunt. It uses remote state from previous step.

```bash
cd stage/resource_group
terragrunt apply
```

4\. Deploy child module (Azure Storage) which depends on parent.

```bash
cd stage/storage_account
terraform apply
```

Expected result: Terragrunt does `terraform output` first thing in the parent module directory to get outputs required for the child module.

Actual result: Terragrunt does `terraform init` in the parent module directory.

It seriously slows down working with modules that depend on other modules. Every time I run e.g. `terragrunt plan` in the child module it takes an extra minute to `terraform init` in the parent module.

Thanks!

**Comment by brikis98** [comment] 2020-12-01 10:13
`output` only works if `init` has been run previously... So I think it is required to run it if it hasn't been run before.

BTW, in your examples, did you mean `terraform apply` or `terragrunt  apply`?

**Comment by maximivanov** [comment] 2020-12-01 12:35
To deploy a remote state storage container used in later steps, I use `terraform ...` since there's no real benefit in using Terragrunt in this case. 

Later steps where I create resources for the `stage` environment are using `terragrunt ...`.

Re `output` and `init` - it definitely needs to run for the first time. But does it have to run each time I run `terraform plan` in a dependent module?

```bash
cd stage/storage_account # child module which depends on parent (resource_group) module
terragrunt plan # will trigger terraform init in parent resource_group module
terragrunt plan # once again will trigger terraform init in the parent
```

**Comment by yorinasub17** [comment] 2020-12-01 15:07
This is related to https://github.com/gruntwork-io/terragrunt/issues/1322. The issue is that to avoid parsing the full terragrunt config, we need to run init with just the remote state block. This approach is much faster when you have nested dependencies, but can be slow for situations where the dependencies are shallow.

You can try switching to the old way of full parsing by setting `disable_dependency_optimization = false` on your `remote_state` block, which will avoid the `init`, but in turn will recursively call `terragrunt output` on each dependency.

**Comment by maximivanov** [comment] 2020-12-01 18:29
Thanks @yorinasub17. I guess you meant setting `disable_dependency_optimization = true`. That helped and shaved off extra 30 to 60 seconds from `terragrunt plan` execution time for me. Great to see #1322 in planned. Cheers!

**Comment by yorinasub17** [comment] 2020-12-01 21:13
Ah yes I meant set to `true`... Updated original comment. Thanks for pointing that out!

**Comment by brikis98** [comment] 2020-12-02 08:58
OK, closing in favor off #1322.

**Closed by brikis98** 2020-12-02 08:58 UTC
Labels: question
