### ISSUE TITLE
remote_state with backend type of "remote" doesn't work

### ISSUE THREAD

**Issue by robbruce** [gruntwork-io/terragrunt#1341] opened 2020-09-13 16:07 UTC
In order to use the terraform remote state backend of type `remote`, the resulting terraform config should look like this:

```terraform
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "my-org"
    
    workspaces {
      name = "workspace-name"
    }
  }
}
```

In order to generate using the `remote_state` block, this would require config like this

```hcl
remote_state {
  backend = "remote"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    hostname     = "app.terraform.io"
    organization = "my-org"

    workspaces {
      name = "workspace-name"
    }
  }
}
```

Obviously, generating `workspace-name` with a dynamic value. However when supplying the above, the following occurs

```
Missing key/value separator; Expected an equals sign ("=") to mark the beginning of the attribute value.
```

When changing to a supported terragrunt config, such as

```hcl
remote_state {
  backend = "remote"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    hostname     = "app.terraform.io"
    organization = "my-org"

    workspaces = {
      name = "workspace-name"
    }
  }
}
```

This results in invalid terraform code and yields the error

```
Error: Unsupported argument

  on backend.tf line 5, in terraform:
   5:     workspaces = {
```

A terragrunt generate block can be used instead, but in doing I've been unable to get the dependency/mocked outputs to work as the remote state does not exist with any data.

**Comment by brikis98** [comment] 2020-09-14 13:00
I believe this is a duplicate of #779.

**Closed by brikis98** 2020-09-14 13:00 UTC
Labels: bug, help wanted
