### ISSUE TITLE
terraform.TgApplyAll(t, terraformOptions) is failing to perform --terragrunt-include-external-dependencies operation

### ISSUE THREAD

**Issue by pandu-bhojaraj-mf** [gruntwork-io/terragrunt#1417] opened 2020-11-05 07:32 UTC
@bruno @yorinasub17 @yupvr 

1. 
If i run **terragrunt apply-all --terragrunt-non-interactive** command manually from **command line** then I am getting below error

![image](https://user-images.githubusercontent.com/73541850/98210373-80070100-1f66-11eb-8845-5b7bd3812d89.png)

2.
If i run below command manually from **command line** then I am getting positive response **without any error**

**terragrunt apply-all --terragrunt-non-interactive --terragrunt-include-external-dependencies**

3.
But if i invoke same module from terratest using **terraform.TgApplyAll(t, terraformOptions)** function then i am getting below **error same error as** of #**1** 

![image](https://user-images.githubusercontent.com/73541850/98210571-c2c8d900-1f66-11eb-979b-a608f375432f.png)

4. 
So In terratest please let me know how can i run **terragrunt apply-all --terragrunt-non-interactive --terragrunt-include-external-dependencies** because **terraform.TgApplyAll(t, terraformOptions)** is not solving the problem
Are there any way/option/modifications do i need to do in terraform.TgApplyAll(t, terraformOptions) function to pass **--terragrunt-include-external-dependencies** ??

Please help

**Comment by robmorgan** [comment] 2020-11-05 08:19
Closing this issue as the problem is related to Terratest, not Terragrunt. Please see this issue for further information: https://github.com/gruntwork-io/terratest/issues/514

**Closed by robmorgan** 2020-11-05 08:19 UTC

**Comment by pandu-bhojaraj-mf** [comment] 2020-11-05 09:13
This issue is not yet resolved

**Comment by robmorgan** [comment] 2020-11-09 09:26
Hi @pandu-bhojaraj-mf, this is an upstream issue in Terratest and we must address it there instead. Please refer to https://github.com/gruntwork-io/terratest/issues/514.
