### ISSUE TITLE
run_cmd should stop execution if stderr is not empty

### ISSUE THREAD

**Issue by tiwood** [gruntwork-io/terragrunt#755] opened 2019-06-18 17:05 UTC
Hi,

we're running an external program to get parameters/settings from a central location. Our program returns an error (stderr and exit code > 0) if for some reason the value is not available for the user.

Unfortunately this is currently not honoured by Terragrunt therefore the execution continues even if the program ran by run_cmd failed.

I can create an PR to add this functionality, but what should be the default behaviour?

- Ignore STDERR and continue (current)
- Stop execution on STDERR

Optional: We can add a bool at the beginning of the interpolation so the user can decide if STDERR outputs should stop the execution. Like so: `run_cmd(false, "echo", "foobar")`

**Comment by yorinasub17** [comment] 2019-06-21 04:53
I don't think it is the right behavior to assume outputs to `stderr` mean the command failed. Many programs use `stderr` for log output (esp. debug and warnings) even for successful execution, including `terragrunt` itself.

However, `run_cmd` should definitely halt execution if there is an error in the underlying command (exit code != 0). A PR to fix that is very welcome!

**Comment by levkohimins** [comment] 2023-09-16 00:11
Just checked, `terragrunt` halts execution if the `run_cmd` command returns an exit code other than 0.
Thus, the issue is considered resolved, closing it.

**Closed by levkohimins** 2023-09-16 00:11 UTC
Labels: bug
