### ISSUE TITLE
Hidden file not copied

### ISSUE THREAD

**Issue by mazzy89** [gruntwork-io/terragrunt#437] opened 2018-03-15 12:36 UTC
I have a module which has a file named `.npmrc`. It is important to provision correctly the module. Once the module is retrieved from git by Terragrunt the hidden "stuff" are not copied as said in [here](https://github.com/gruntwork-io/terragrunt/blob/7fbf2c148beedbc5421974603220afa535e1d208/test/fixture-download/local-with-hidden-folder/.hidden-folder/README.md).

Any ways to control this behaviour?

**Comment by brikis98** [comment] 2018-03-15 12:41
Duplicate of #394. PR to fix this issue is very welcome.

**Closed by brikis98** 2018-03-15 12:41 UTC
