### ISSUE TITLE
Bugs in render-json command?

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#2189] opened 2022-07-12 13:44 UTC
It seems like the `render-json` command has a couple bugs:

1. It doesn't output any info about `dependency` blocks.
2. The `locals` map is `null` even when local vars are set.

I created a small repo to test with here: https://github.com/brikis98/render-json-bug-repro. To reproduce the issue, run `terragrunt render-json` in the root of that repo.

The output I get looks like this:

```json
{
  "dependencies": null,
  "download_dir": "",
  "generate": {
    "provider": {
      "comment_prefix": "# ",
      "contents": "# This is just a test",
      "disable_signature": false,
      "if_exists": "overwrite",
      "path": "provider.tf"
    }
  },
  "iam_assume_role_duration": null,
  "iam_assume_role_session_name": "",
  "iam_role": "",
  "inputs": {
    "another": "baz",
    "baz": "blah",
    "foo": "bar",
    "from_root": "Hi"
  },
  "locals": null,
  "retry_max_attempts": null,
  "retry_sleep_interval_sec": null,
  "retryable_errors": null,
  "skip": false,
  "terraform": {
    "after_hook": {},
    "before_hook": {},
    "error_hook": {},
    "extra_arguments": {},
    "include_in_copy": null,
    "source": "./foo"
  },
  "terraform_binary": "",
  "terraform_version_constraint": "",
  "terragrunt_version_constraint": ""
}
```

Even though the module has a `dependency` block and local variables defined, I don't see either in the output.

**Comment by yorinasub17** [comment] 2022-07-13 15:02
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.38.5

**Comment by lachlankrautz** [comment] 2022-07-13 16:29
That release seems to introduce this issue not solve it. I'm getting `{"locals": null}` on `v0.38.5` and wasn't before..

**Comment by yorinasub17** [comment] 2022-07-13 19:49
@lachlankrautz do you have a minimum reproducible case we can use to debug the issue you are seeing? The latest version outputs the `locals` properly in the referenced repo from OP, and also in a few examples I have.

**Comment by lachlankrautz** [comment] 2022-07-14 05:21
Steps to reproduce just using the terragrunt-infrastructure-live-example

```shell
git clone git@github.com:gruntwork-io/terragrunt-infrastructure-live-example.git
cd terragrunt-infrastructure-live-example/prod/us-east-1/prod/mysql
terragrunt render-json --terragrunt-json-out /dev/stdout | jq -r '.locals'
```

Output
```shell
null
````

Output previous to this version:
````shell
{
  "account_id": "replaceme",
  "account_name": "prod",
  "account_vars": {
    "dependencies": null,
    "download_dir": "",
    "generate": {},
    "iam_assume_role_duration": null,
    "iam_assume_role_session_name": "",
    "iam_role": "",
    "inputs": null,
    "locals": {
      "account_name": "prod",
      "aws_account_id": "replaceme",
      "aws_profile": "prod"
    },
    "retry_max_attempts": null,
    "retry_sleep_interval_sec": null,
    "retryable_errors": null,
    "skip": false,
    "terraform_binary": "",
    "terraform_version_constraint": "",
    "terragrunt_version_constraint": ""
  },
  "aws_region": "us-east-1",
  "environment_vars": {
    "dependencies": null,
    "download_dir": "",
    "generate": {},
    "iam_assume_role_duration": null,
    "iam_assume_role_session_name": "",
    "iam_role": "",
    "inputs": null,
    "locals": {
      "environment": "prod"
    },
    "retry_max_attempts": null,
    "retry_sleep_interval_sec": null,
    "retryable_errors": null,
    "skip": false,
    "terraform_binary": "",
    "terraform_version_constraint": "",
    "terragrunt_version_constraint": ""
  },
  "region_vars": {
    "dependencies": null,
    "download_dir": "",
    "generate": {},
    "iam_assume_role_duration": null,
    "iam_assume_role_session_name": "",
    "iam_role": "",
    "inputs": null,
    "locals": {
      "aws_region": "us-east-1"
    },
    "retry_max_attempts": null,
    "retry_sleep_interval_sec": null,
    "retryable_errors": null,
    "skip": false,
    "terraform_binary": "",
    "terraform_version_constraint": "",
    "terragrunt_version_constraint": ""
  }
}
```

**Comment by yorinasub17** [comment] 2022-07-14 14:39
Thanks for the example.

The new behavior is actually the desired behavior here, primarily because the `locals` should only show up in the context of where they are defined. Those locals are actually not available in the context of the child config because they are defined in the parent (e.g., if you did `local.region_vars` in the child config, it will fail).

The intention is for `render-json` to show what is in scope in the current config, as rendered, so it is more correct that it omits those because they are not accessible.

Hope that makes sense! If there is a need to see those locals from the parent, then I think this makes sense to add in the `--with-metadata` feature referenced in https://github.com/gruntwork-io/terragrunt/issues/2196

In the meantime, the workaround is to run `render-json` on the included config, which you should be able to identify from the `include` attribute.

**Closed by yorinasub17** 2022-07-14 14:39 UTC
Labels: bug
