### ISSUE TITLE
New feature: refresh-all

### ISSUE THREAD

**Issue by francoisregnoult** [gruntwork-io/terragrunt#1474] opened 2020-12-29 22:36 UTC
I don't know if I'm under a bug but I had some issues with outputs when the parent has had a new output since last plan/apply.

The resolution I found was to run "terragrunt resfresh" in the dependancy folder. Sometimes I've modified multiple dependancies and I need to run that in each dependancy.

Sadly I can't find an option to run that "globally". I think it would work in the same way and dependancy order than "apply-all" but to run "refresh" in the account. The option would be "refresh-all"

**Comment by yorinasub17** [comment] 2021-01-04 19:38
I will mark this as a duplicate of https://github.com/gruntwork-io/terragrunt/issues/492, as we want to implement a generic `xxx-all` version as opposed to duplicating more commands, and this should include `refresh`. You can follow that ticket for updates on when we implement something like this. Given the maintainability of these commands, we most likely won't be adding additional commands like `refresh-all` or `init-all` until we find a way to make it generic.

Note that this is actually expected behavior as terragrunt dependencies reads the outputs out of the state file, so naturally you need to run `refresh` or `apply` everytime the outputs change to get the outputs stored in the state file.

**Closed by yorinasub17** 2021-01-04 19:38 UTC
