### ISSUE TITLE
Severe Performance Issues: O(n^2) Redundancy in Terragrunt Locals and Root Includes

### ISSUE THREAD

**Issue by swordfish444** [gruntwork-io/terragrunt#3153] opened 2024-05-22 17:16 UTC
## Describe the bug

**[Update - 2024-06-06] We've identified Terragrunt's AWS Role-based authentication is 300% slower than with standard authentication. 150s (role-based) vs 50s (standard)**

The performance of my Terragrunt repository is extremely slow due to the use of composable files that help separate static vs. user-provided inputs, promote reuse, and simplify downstream modules. The repository makes use of all environment shared inputs and locals (root.hcl), which resides in `tg-repo/live/root.hcl`. The `root.hcl` includes `tg-repo/live/static_maps.hcl` and `tg-repo/live/common.hcl` and constructs a final combined inputs and locals, which are used in downstream modules.

Downstream modules use:
```hcl
include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}
```
and reference locals and inputs, for example: `include.root.locals.skip_dep_outputs`.

As the repository grows in modules and dependencies between modules, the time it takes Terragrunt to load all locals and recursively traverse all dependencies and their respective `root.hcl` -> `static_maps.hcl` -> `common.hcl` has grown exponentially. It's not uncommon to wait 2 minutes for it to simply load the locals when running a `terragrunt plan` or `terragrunt apply`.

The performance slowdown is definitely caused by the use of multiple root includes, which are also present in each dependent module. This results in a cascading issue with time and space complexity of:

```
  O(n * d * l) 
```

... where worst-case is

```
  O(n^2)
```

Where:

* n is the number of modules.
* d is the number of dependencies each module has.
* l is the number of locals and inputs to evaluate.

## Steps To Reproduce

Steps to reproduce the behavior, code snippets, and examples which can be used to reproduce the issue. Because this repo is hooked up to AWS and relies on private Gitlab terraform modules, it's not possible to give you the exact codebase to reproduce. 
1. Set up a Terragrunt repository with the following structure:
    ```
    tg-repo/
    ├── live/
    │   ├── root.hcl
    │   ├── static_maps.hcl
    │   ├── common.hcl
    │   └── ... (various modules and dependencies)
    ```

<img width="184" alt="image" src="https://github.com/gruntwork-io/terragrunt/assets/3893966/5a81b3c8-8ea6-4ff4-9b95-a1292f563ee3">

2. Include `root.hcl` in downstream modules with:
    ```hcl
    include "root" {
      path   = find_in_parent_folders("root.hcl")
      expose = true
    }
    ```

3. Run `terragrunt plan` or `terragrunt apply` on a module that includes the `root.hcl`.

Example of `live/dev/services/api/shared.hcl`:

<img width="490" alt="image" src="https://github.com/gruntwork-io/terragrunt/assets/3893966/9bde1480-891a-4429-9f37-b22346228c9e">

The `shared.hcl` file is then loaded into `live/dev/services/api/terragrunt.hcl` as observed here:

```hcl
include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

locals {
  # Read in service-wide "shared" locals
  svc_locals = read_terragrunt_config("${get_terragrunt_dir()}/shared.hcl").locals
  # ....
}
```

I hope this gives you an idea of the *include* fan-out problem I'm experiencing. 

## Expected behavior

I expect Terragrunt to load the locals and traverse dependencies efficiently, without exponential growth in loading times as the repository scales.

## Nice to haves

- [x] Terminal output
- [x] Screenshots

## Versions

- Terragrunt version: v0.58.8
- OpenTofu/Terraform version: Terraform v1.7.3
- Environment details: Mac OS M1

## Additional context

Here is an analysis of the debug logs while running terragrunt plan in one of the downstream modules `live/dev/services/api/monitor/terragrunt.hcl`:

### Log Analysis Summary

**Terragrunt Version**: 0.58.8

**Total Locals Evaluated**: 2195

#### Performance Issues
- **Locals Block Evaluations**: The log shows that locals blocks are evaluated 2195 times, which is a significant number and indicates that the configuration has high redundancy in its evaluations. Each locals block evaluation likely contributes to a high time complexity.
- **Root Includes and Dependencies**: The performance slowdown is primarily due to multiple root includes, which are found in each dependent module. This creates a cascading effect, where each root include triggers evaluations in all dependent modules, leading to an exponential growth in the number of evaluations.

#### Time Complexity
- **Complexity Analysis**: The problem appears to have a time complexity of O(n^2) or worse, where n is the number of includes and dependencies. This quadratic complexity arises because each root include triggers evaluations across all dependencies, and each dependency may further trigger additional evaluations.

#### Problematic Areas
- **Redundant Evaluations**: The heavy load of locals block evaluations suggests that there are redundant evaluations taking place. These redundant evaluations are likely due to repeated includes and re-evaluation of the same locals blocks across different modules.
- **Locals Block Details**: The log snippet does not provide specific details about which locals blocks are causing the most issues, but the sheer number of evaluations indicates that optimizing these blocks is crucial.

### Counts and Timing
- **Evaluation Counts**: 2195 locals block evaluations are recorded, indicating the scale of redundancy.
- **Timing Details**: While exact timing details are not provided in the log, the high number of evaluations suggests that these operations are time-consuming and contribute significantly to the overall execution time.

### Dependency Diagram
Below is a Mermaid diagram representing the redundancy observed in the evaluations:

```mermaid
graph TD
    A[Root Include A] --> B[Dependent Module 1]
    A --> C[Dependent Module 2]
    A --> D[Dependent Module 3]
    B --> E[Include A]
    B --> F[Include B]
    C --> G[Include A]
    C --> H[Include C]
    D --> I[Include A]
    D --> J[Include D]
    E --> K[Resource 1]
    F --> L[Resource 2]
    G --> M[Resource 1]
    H --> N[Resource 3]
    I --> O[Resource 1]
    J --> P[Resource 4]
```

### Recommendations
- **Optimize Locals Blocks**: Review and optimize locals block evaluations to reduce redundancy. Consider consolidating or reusing evaluated values instead of recalculating them.
- **Refactor Includes**: Reduce the number of root includes and ensure they do not redundantly trigger evaluations in dependent modules. Use a more modular approach to include only necessary evaluations.
- **Community Guidance**: Share this detailed analysis and diagram with the community to seek specific optimization techniques or tools that can help identify and reduce redundant evaluations.

Looking forward to your assistance in how I might continue to build out a large scale terragrunt project in composable parts, but in a way that's performant. 🙇

**Comment by denis256** [comment] 2024-05-24 15:49
Hi,
this are a lot of good things to look into

> Optimize Locals Blocks: Review and optimize locals block evaluations to reduce redundancy. Consider consolidating or reusing evaluated values instead of recalculating them.

In some cases is required to re-evaluate each time included locals, like reading files from project

```
.
├── app
│   ├── app1
│   │   ├── api.yaml
│   │   ├── main.tf
│   │   └── terragrunt.hcl
│   └── app2
│       ├── api.yaml
│       ├── main.tf
│       └── terragrunt.hcl
├── README.md
└── terragrunt.hcl


# terragrunt.hcl

locals {
  config = yamldecode(file("${get_terragrunt_dir()}/api.yaml"))
}

inputs = {
  api_key = local.config.api_key
}
```
https://github.com/denis256/terragrunt-tests/tree/master/locals-evaluation

**Comment by swordfish444** [comment] 2024-05-29 17:37
@yhakbar 

> Do you mind sharing how you're calling Terragrunt right now? Is my assumption right that you're calling run-all commands from your root terragrunt.hcl file when you see these issues?

Here is the command I'm running:

```shell
terragrunt apply
```

Some additional details:

* Storing state in S3
* All of our modules depend on AWS provider

I was not using `--terragrunt-use-partial-parse-config-cache`, but I tested it just now and it didn't help 😢.

What we did find so far is that the initialization time took 300% longer when using `aws sso` with an AWS role for AWS CLI authentication as opposed to just using direct AWS ENV credentials. The time increased from 50 seconds to 150 seconds. 

Even 50 seconds is excessive, but at least it's bearable. It seems like there are some good optimizations that can be done with the AWS role-based authentication in Terragrunt code.

> Also, do you mind sharing how you've investigated your performance issues? Are you leveraging the [OpenTelemetry Integration](https://terragrunt.gruntwork.io/docs/features/debugging/#opentelemetry-integration) to get insight into your performance issues?

This is a great recommendation. No, we have not used this. I will look into this and report back with any new insights.

**Comment by caspar-ds** [comment] 2024-06-05 10:45
Is this linked to #2980?

**Comment by swordfish444** [comment] 2024-06-06 16:35
@caspar-ds 
> Is this linked to #2980?

There is definitely overlap. One of the unique aspects surfaced in this issue is how inefficient Terragrunt's  _AWS Role-based authentication_ is:

> What we did find so far is that the initialization time took 300% longer when using `aws sso` with an AWS role for AWS CLI authentication as opposed to just using direct AWS ENV credentials. The time increased from 50 seconds to 150 seconds.

**Comment by swordfish444** [comment] 2024-06-06 16:42
Made an update to the description, surfacing the extreme degradation in performance when using AWS role-based authentication when compared to default authn.

**Comment by yhakbar** [comment] 2024-06-17 14:07
Thanks for all of your feedback, everyone. We appreciate that you are all so invested in improving the performance of Terragrunt and we are paying close attention to the feedback you have provided.

Special thanks to @swordfish444 for opening this issue, and doing some hard work diagnosing the root cause of your performance issues, and providing us with clues that we were able to use to look more closely at the source code and attempt to address inefficiencies in how certain operations are handled. Specifically pointing out we had an opportunity to speed up operations related to role assumptions and state management gave us insight that the optimizations in [v0.59.1](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.59.1) might help.

I want to be clear that those optimizations are to reduce unnecessary overhead in what Terragrunt does to initialize state and assume roles, however it will always be faster to not use Terragrunt for role assumption and assume the role outside of Terragrunt, as doing no work is always faster than doing work. If you are struggling with performance issues related to role assumptions taking place in Terragrunt, and you have the option to assume the role outside of Terragrunt, that will always result in Terragrunt being faster.

With respect to memoizing rendering of local parsing, please take note of @denis256's comment up [here](https://github.com/gruntwork-io/terragrunt/issues/3153#issuecomment-2129869709). Terragrunt cannot fully reproduce the a previously parsed HCL include, because of the nature of HCL files. They allow for dynamic content, and reproducing the same output for an HCL parse will likely result in bugs for users. Note that there are optimizations that we can perform for this, and [do](https://github.com/gruntwork-io/terragrunt/blob/2d864f5edc7890684ae4646989bad4c4e65bf1fb/config/config.go#L723-L728), but each read of an HCL file ultimately requires doing some additional work to ensure that the values from the file are up to date.

If any other specific recommendations for performance improvements come to mind, or particular circumstances where Terragrunt is slower than expected, please share them here.

I will be closing out this issue in about a week if nothing actionable comes up to avoid having this issue go stale.

Afterwards, please look to @swordfish444's great example on how to present performance issues in a way that is actionable and helpful for the maintainers to address. I plan in improving Terragrunt documentation on bug reporting to use this approach as a template.

**Comment by jtackaberrybb** [comment] 2024-06-17 15:40
> With respect to memoizing rendering of local parsing, please take note of @denis256's comment up https://github.com/gruntwork-io/terragrunt/issues/3153#issuecomment-2129869709. Terragrunt cannot fully reproduce previously parsed HCL include, because of the nature of HCL files. They allow for dynamic content, and reproducing exactly the same output for an HCL parse from cache will likely result in bugs for users.

I can definitely understand that locals would need to be reevaluated based on each relative starting point.  So in @denis256's example, if app2 depended on app1, then when running terragrunt from app2, the root-level terragrunt.hcl would be evaluated from both app2's perspective and app1's perspective.  Makes sense.

Are there other factors that confound locals memoization?

**Comment by jtackaberry** [comment] 2024-06-17 15:41
> With respect to memoizing rendering of local parsing, please take note of @denis256's comment up https://github.com/gruntwork-io/terragrunt/issues/3153#issuecomment-2129869709. Terragrunt cannot fully reproduce previously parsed HCL include, because of the nature of HCL files. They allow for dynamic content, and reproducing exactly the same output for an HCL parse from cache will likely result in bugs for users.

I can definitely understand that locals would need to be reevaluated based on each relative starting point.  So in @denis256's example, if app2 depended on app1, then when running terragrunt from app2, the root-level terragrunt.hcl would be evaluated from both app2's perspective and app1's perspective.  Makes sense.

Are there other factors that confound locals memoization?

**Comment by jtackaberry** [comment] 2024-06-17 16:05
> We can cache the AST body of the file (that it has a locals block with a current_time local, which calls run_cmd on date), so we can skip the filesystem read penalty the next parse, but we have to actually run the function on every parse to make sure the result is accurate.

This makes sense, thanks @yhakbar.

Is this something `--terragrunt-use-partial-parse-config-cache` would cache, and the potential expense of correctness?

This is the type of thing I'm fairly sure our projects could safely cache.  The network calls as well are extremely costly, especially over latent connections, but I see no reason we couldn't safely cache that.  Looking through our project code, AFAICT if everything was evaluated once and cached, the result would still be sane.  And if the network calls were cached, my guess is an order of magnitude reduction in execution time, which is a benefit I would be willing to pay for in the form of less dynamic magic.

**Comment by yhakbar** [comment] 2024-06-21 13:54
@jtackaberry 

Rather than respond directly, I've updated documentation to hopefully make it clearer to everyone what the flag caches so that we can help others understand what the trade-off is for the [--terragrunt-use-partial-parse-config-cache flag](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-use-partial-parse-config-cache). Please take a read and let me know if I can further clarify that piece of documentation.

I would need more details to be able to provide more useful feedback on the issues that you're experiencing with respect to the costly network calls impacting performance. Things like how the calls are being made (via a `dependency` block, a `run_cmd` call, a `read_terragrunt_config` call, etc) and why the call is being repeated even though it can be safely re-used would be useful info.

**Comment by yhakbar** [comment] 2024-06-24 19:01
As discussed earlier, I'm closing out this issue. Please open up a new one if you would like to provide insight as to how the performance of Terragrunt can be improved going forward!

**Closed by yhakbar** 2024-06-24 19:01 UTC
Labels: bug

**Comment by apshoemaker** [comment] 2024-08-09 18:59
This really needs to be reopened - the newer versions of terragrunt are painfully much slower than anything in the 0.50.x range and older.  I would love to use your later featureset, but can't take the operational hit of several minutes to apply relatively simple infrastructure mutations.  Any thoughts?  Do you prefer a new issue to track to completion?

**Comment by yhakbar** [comment] 2024-08-09 19:05
Hey @apshoemaker , what is the latest version of Terragrunt that you've tried?

Have you tried [v0.66.3](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.66.3)? Some great work was done in that release to improve performance significantly for many users.
