### ISSUE TITLE
Terragrunt downloads unaccessible

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [gruntwork-io/terragrunt#1171] opened 2020-05-07 22:33 UTC
Hi! I'm trying to download terragrunt as part of my CI/CD pipeline and am getting errors.

It seems that terragrunt releases from Github are currently not available. Looks to be an issue with S3/AWS.

This is the output when clicking any of the downloads from the latest release via Github. E.G. [Linux AMD 64](https://github.com/gruntwork-io/terragrunt/releases/download/v0.23.14/terragrunt_linux_amd64)

I've verified on linux, mac, and windows on different networks.

```xml
<Error>
   <Code>SignatureDoesNotMatch</Code>
   <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
   <AWSAccessKeyId>REDACTED</AWSAccessKeyId>
   <StringToSign>AWS4-HMAC-SHA256 20200507T222358Z 20200507/us-east-1/s3/aws4_request 4ec3f1bc54f9d36306e9a9655babdf9eb3307ea0fdd0449ee4a3d12ae993282b</StringToSign>
   <SignatureProvided>08470fd997eaa1b622834cf327e3dfdd489311a73588a6606b9fd58b7794dc73</SignatureProvided>
   <StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 30 30 35 30 37 54 32 32 32 33 35 38 5a 0a 32 30 32 30 30 35 30 37 2f 75 73 2d 65 61 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 34 65 63 33 66 31 62 63 35 34 66 39 64 33 36 33 30 36 65 39 61 39 36 35 35 62 61 62 64 66 39 65 62 33 33 30 37 65 61 30 66 64 64 30 34 34 39 65 65 34 61 33 64 31 32 61 65 39 39 33 32 38 32 62</StringToSignBytes>
   <CanonicalRequest>GET /59522149/9a04e980-369d-11ea-903c-b5031f171754 X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REDACTED%2F20200507%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200507T222358Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&actor_id=0&repo_id=59522149&response-content-disposition=attachment%3B%20filename%3Dterragrunt_linux_amd64&response-content-type=application%2Foctet-stream host:github-production-release-asset-2e65be.s3.amazonaws.com host UNSIGNED-PAYLOAD</CanonicalRequest>
   <CanonicalRequestBytes>47 45 54 0a 2f 35 39 35 32 32 31 34 39 2f 39 61 30 34 65 39 38 30 2d 33 36 39 64 2d 31 31 65 61 2d 39 30 33 63 2d 62 35 30 33 31 66 31 37 31 37 35 34 0a 58 2d 41 6d 7a 2d 41 6c 67 6f 72 69 74 68 6d 3d 41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 26 58 2d 41 6d 7a 2d 43 72 65 64 65 6e 74 69 61 6c 3d 41 4b 49 41 49 57 4e 4a 59 41 58 34 43 53 56 45 48 35 33 41 25 32 46 32 30 32 30 30 35 30 37 25 32 46 75 73 2d 65 61 73 74 2d 31 25 32 46 73 33 25 32 46 61 77 73 34 5f 72 65 71 75 65 73 74 26 58 2d 41 6d 7a 2d 44 61 74 65 3d 32 30 32 30 30 35 30 37 54 32 32 32 33 35 38 5a 26 58 2d 41 6d 7a 2d 45 78 70 69 72 65 73 3d 33 30 30 26 58 2d 41 6d 7a 2d 53 69 67 6e 65 64 48 65 61 64 65 72 73 3d 68 6f 73 74 26 61 63 74 6f 72 5f 69 64 3d 30 26 72 65 70 6f 5f 69 64 3d 35 39 35 32 32 31 34 39 26 72 65 73 70 6f 6e 73 65 2d 63 6f 6e 74 65 6e 74 2d 64 69 73 70 6f 73 69 74 69 6f 6e 3d 61 74 74 61 63 68 6d 65 6e 74 25 33 42 25 32 30 66 69 6c 65 6e 61 6d 65 25 33 44 74 65 72 72 61 67 72 75 6e 74 5f 6c 69 6e 75 78 5f 61 6d 64 36 34 26 72 65 73 70 6f 6e 73 65 2d 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3d 61 70 70 6c 69 63 61 74 69 6f 6e 25 32 46 6f 63 74 65 74 2d 73 74 72 65 61 6d 0a 68 6f 73 74 3a 67 69 74 68 75 62 2d 70 72 6f 64 75 63 74 69 6f 6e 2d 72 65 6c 65 61 73 65 2d 61 73 73 65 74 2d 32 65 36 35 62 65 2e 73 33 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 0a 68 6f 73 74 0a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44</CanonicalRequestBytes>
   <RequestId>A872F89A0EE9E5B9</RequestId>
   <HostId>dlMfTCYxEG14cBla5VWU15rwBSaj90g/K5KACeFHsvrMIUotCciUxvobUO0UO+p8J+/5KQVV0cc=</HostId>
</Error>
```

**Comment by AwolDes** [comment] 2020-05-07 22:53
I've also received a similar error to @rafmagns-skepa-dreag in my CI pipeline when we download Terragrunt.

```bash
WARN: Redirected to https://github-production-release-asset-2e65be.s3.amazonaws.com/59522149/eb1181fa-39ae-11e8-8400-991f325c9425?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXX%2F20200507%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200507T222732Z&X-Amz-Expires=300&X-Amz-Signature=XXXXX&X-Amz-SignedHeaders=host&actor_id=0&repo_id=59522149&response-content-disposition=attachment%3B+filename%3Dterragrunt_linux_amd64&response-content-type=application%2Foctet-stream

Net::HTTPServerException: 403 "Forbidden"
```

This seems to have happened between 7am-8am AEST (1-2 hours ago)

**Comment by yorinasub17** [comment] 2020-05-07 23:09
I believe this is a site wide issue with github. There are multiple reports on twitter with the same error on a range of repos.

**Comment by AwolDes** [comment] 2020-05-07 23:10
@yorinasub17 I was wondering if that might be the case. Thanks for adding an update :+1:

**Comment by AwolDes** [comment] 2020-05-07 23:24
Yep looks like a GitHub level issue - https://www.githubstatus.com/incidents/1p369ttzrnqy

This issue can probably be closed

**Comment by yorinasub17** [comment] 2020-05-08 01:02
Closing as the github issue is resolved and confirmed downloads are working.

**Closed by yorinasub17** 2020-05-08 01:02 UTC
