### ISSUE TITLE
Support for OpenTF

### ISSUE THREAD

**Issue by plachkov** [gruntwork-io/terragrunt#2723] opened 2023-09-19 08:35 UTC
Since HashiCorp switched the license for Terraform from the Mozilla Public License to the Business Source License, are you planning to support OpenTF? 
https://opentf.org/
https://github.com/opentffoundation/opentf

**Comment by denis256** [comment] 2023-09-19 17:26
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/2690

**Closed by denis256** 2023-09-19 17:26 UTC
Labels: enhancement
