### ISSUE TITLE
Allow for a simple "terragrunt lock" command

### ISSUE THREAD

**Issue by mioi** [gruntwork-io/terragrunt#46] opened 2016-11-04 17:29 UTC
It would very helpful if we can create a `terragrunt lock` without performing any other operation.

The use case is, during the time between when **User 1** does a `terragrunt plan` and does the subsequent `terraform apply`, someone _else_ (**User 2**) could come in and do a `plan` + `apply`. This could create a situation where the outcome of **User 1**'s `apply` results in something unexpected. If **User 1** could create the lock before doing anything, that would ensure that only one user was doing anything terraform-related.

**Comment by brikis98** [comment] 2016-11-04 17:40
It's worth mentioning that you can save the output of the `plan` command to a file and then run `apply` on that file to ensure that you make exactly the changes you expect. That said, long-term locking would still be useful, so I'm totally in favor of a `terragrunt lock` command. 

I'm going to close this because it's a duplicate of #19, but let's continue the conversation there.

**Closed by brikis98** 2016-11-04 17:40 UTC
