### ISSUE TITLE
get_parent_terragrunt_dir() returns wrong path

### ISSUE THREAD

**Issue by tiwood** [gruntwork-io/terragrunt#756] opened 2019-06-18 19:20 UTC
Hi,

I'm currently in the process of upgrading our Terragrunt/Terraform setup.

We have the following folder structure:
```
.
├── environments
│   └── core
│       └── workloads
│           ├── terragrunt.hcl
│           └── workloads.tf.tpl
├── global
│   ├── foo
│   │   └── bar.ps1
└── terragrunt.hcl
```

We have hooks in the parent `terragrunt.hcl` as well as in the `terragrunt.hcl` in the `workloads` folder.

Our hook (**defined in the child terragrunt.hcl**) should run a script in the global folder but fails as the wrong path is provided by `get_parent_terragrunt_dir()`. This is the hook definition:
```hcl
before_hook "prepare_workloads" {
    commands = get_terraform_commands_that_need_vars()

    execute = [
      "pwsh",
      "-nop",
      "-nol",
      "-File",
      "${get_parent_terragrunt_dir()}/global/foo/bar.ps1",
    ]

    run_on_error = false
  }
```

This fails as `get_parent_terragrunt_dir()` returns `/environments/core/workloads` instead of `/`. 

I've created a test hook with both interpolations:
```hcl
before_hook "test" {
    commands = get_terraform_commands_that_need_vars()

    execute = [
      "echo",
      "${get_terragrunt_dir()}",
      "${get_parent_terragrunt_dir()}"
    ]

    run_on_error = false
  }
```

This is the output:
```
[terragrunt] 2019/06/18 21:14:55 Executing hook: test
[terragrunt] 2019/06/18 21:14:55 Running command: echo /environments/core/workloads /environments/core/workloads
/environments/core/workloads /environments/core/workloads
```

I've tried both from the parent file with `terragrunt plan-all`and with `terragrunt` in the `workloads` folder.

**Comment by yorinasub17** [comment] 2019-06-21 04:46
Can you share the contents of the `include` block in the child's `terragrunt.hcl` file?

**Comment by tiwood** [comment] 2019-06-21 06:10
Sure, this is from the child `terragrunt.hcl`:

```hcl
include {
  path = find_in_parent_folders()
}
```

**Comment by yorinasub17** [comment] 2019-06-21 06:27
Thanks I was able to reproduce this and this is indeed a bug. Will start working on a fix.

**Comment by yorinasub17** [comment] 2019-06-21 07:22
Actually, I just realized that this was a misunderstanding on my part. After starting the implementation and digging deeper into the code and rereading our docs, I realized that the `get_parent_terragrunt_dir` only works in the *included config*. In other words, this functions is meant to be used in the context of the parent `terragrunt.hcl` file, not the child's terragrunt file.

Instead, you should actually reuse `find_in_parent_folders` in combination with `dirname` (`dirname(find_in_parent_folders())`) which was included in tg 0.19.4. If you need an absolute path, you can combine it with `get_terragrunt_dir`: `${get_terragrunt_dir()}/${dirname(find_in_parent_folders())}`.

**Comment by yorinasub17** [comment] 2019-06-21 07:25
I can see a function that returns the absolute path to the parent terragrunt config folder being useful, so I will keep this open, but since there is a workaround, I will not be implementing that at the moment. I might pick this up again if I have time in a few weeks.

**Comment by brikis98** [comment] 2019-06-21 13:42
Is this the same issue fixed by https://github.com/gruntwork-io/terragrunt/pull/753?

**Comment by yorinasub17** [comment] 2019-06-21 16:08
Ah I think you are right @brikis98 !

**Comment by brikis98** [comment] 2019-06-21 22:48
Could you give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.5 a shot (new binaries should show up shortly)?

**Comment by seppi91** [comment] 2019-09-25 15:53
Hi,
I think my issue is similar to the one of OP

```
.
├── environments
│   ├── rc.yml
│   └── dev.yml
│── eu-central-1
│   └── component
│          └── terragrunt.hcl
└── terragrunt.hcl
```

my parent terragrunt.hcl has something like this:
```
...
locals {
  env = yamldecode(file("${get_terragrunt_dir()}/${find_in_parent_folders(join("/", ["environments",get_env("ENVIRONMENT", "dev.yml")]))}"))
}

inputs = {
  environment_code = local.env.naming.environment_code
...
```

as locals are not propagated to child terragrunt.hcl I have to parse the yaml file again. So my child terragrunt.hcl looks like

```
include {
  path = find_in_parent_folders()
}

...

locals {
  env = yamldecode(file("${get_terragrunt_dir()}/${find_in_parent_folders(join("/", ["environments",get_env("ENVIRONMENT", "dev.yml")]))}"))
}

inputs = {
 app_settings = merge(local.env.vars, {
    "LOG_LEVEL"       = 2
  })
}
```

when running terragrunt plan within the child working directory everything runs smooth. But when doing a terragrunt plan-all from the parent dir, it breaks (replaced the full path output with placeholders):

> Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a environments/dev.yml in any of the parent folders of
> <PATH_TO_ROOT_TERRAGRUNT> Cause: Traversed all the way to the root..
> 
> [terragrunt] [<PATH_TO_ROOT_TERRAGRUNT_DIR>] 2019/09/25 17:44:20 Encountered error while evaluating locals.
> [terragrunt] 2019/09/25 17:44:20 Error processing module at '<PATH_TO_ROOT_TERRAGRUNT>'. How this module was found: Terragrunt config file found in a subdirectory of <PATH_TO_ROOT_TERRAGRUNT_DIR>. Underlying error: <PATH_TO_ROOT_TERRAGRUNT>:47,52-75: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a environments/dev.yml in any of the parent folders of <PATH_TO_ROOT_TERRAGRUNT>. Cause: Traversed all the way to the root..
> [terragrunt] 2019/09/25 17:44:20 Unable to determine underlying exit code, so Terragrunt will exit with error code

**Comment by yorinasub17** [comment] 2019-09-25 16:04
Ah there is a known issue where you can't use the terragrunt directory related features in `locals`, because of the parsing order: `include` is parsed AFTER `locals`, not before, so unfortunately, you can't actually use functions like `get_terragrunt_dir` currently. See https://github.com/gruntwork-io/terragrunt/issues/814#issuecomment-518919484.

The goal is to introduce a concept like `globals` (https://github.com/gruntwork-io/terragrunt/issues/814) which would address this.

**Comment by yorinasub17** [comment] 2019-10-08 23:31
This is now fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.20.0

**Closed by yorinasub17** 2019-10-08 23:31 UTC
Labels: enhancement, help wanted
