### ISSUE TITLE
Interpolation in tfvars files causes issues even when escaping varables

### ISSUE THREAD

**Issue by jessecollier** [gruntwork-io/terragrunt#465] opened 2018-04-23 22:01 UTC
I would like to pass a template as a variable:
```
my_template = <<EOF
hello my name is ${name}
EOF
```

Yet using terragrunt I get the following:
```
[terragrunt] 2018/04/23 17:54:40 Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${name}'
```

I see this mentioned as a bug here:
https://github.com/gruntwork-io/terragrunt/issues/139#issuecomment-283939341

Wondering if there is something we can do ?

Edit:
I've also tried escaping with double $ `$${name}`... still same issue

**Comment by brikis98** [comment] 2018-04-23 22:40
This is a bug where Terragrunt is processing interpolations outside of the `terragrunt = { ... }` block. Duplicate of #227.

**Closed by brikis98** 2018-04-23 22:40 UTC
Labels: bug
