### ISSUE TITLE
There is no variable named "dependency". Since 0.55.4 upgrade

### ISSUE THREAD

**Issue by ArchiFleKs** [gruntwork-io/terragrunt#2958] opened 2024-02-22 13:24 UTC
**Describe the bug**

Using this file

```
include "root" {
  path           = find_in_parent_folders()
  expose         = true
  merge_strategy = "deep"
}

dependency "vpc" {
  config_path = "../vpc"
}

terraform {
  source = "github.com/terraform-aws-modules/terraform-aws-vpc//modules/vpc-endpoints?ref=v5.5.2"
}

inputs = {
  vpc_id = dependency.vpc.outputs.vpc_id
  endpoints = {
    s3 = {
      service         = "s3"
      service_type    = "Gateway"
      route_table_ids = flatten([dependency.vpc.outputs.private_route_table_ids, dependency.vpc.outputs.public_route_table_ids])
      tags            = { Name = "${include.root.locals.merged.prefix}-${include.root.locals.merged.env}-s3-vpc-endpoint" }
    },
    dynamodb = {
      service         = "dynamodb"
      service_type    = "Gateway"
      route_table_ids = flatten([dependency.vpc.outputs.private_route_table_ids, dependency.vpc.outputs.public_route_table_ids])
      tags            = { Name = "${include.root.locals.merged.prefix}-${include.root.locals.merged.env}-dynamodb-vpc-endpoint" }
    },
    kms = {
      service             = "kms"
      service_type        = "Interface"
      subnet_ids          = flatten([dependency.vpc.outputs.private_subnets])
      security_group_ids  = [dependency.vpc.outputs.default_security_group_id]
      private_dns_enabled = true
      tags                = { Name = "${include.root.locals.merged.prefix}-${include.root.locals.merged.env}-kms-vpc-endpoint" }
    },
    ec2 = {
      service             = "ec2"
      service_type        = "Interface"
      subnet_ids          = flatten([dependency.vpc.outputs.private_subnets])
      security_group_ids  = [dependency.vpc.outputs.default_security_group_id]
      private_dns_enabled = true
      tags                = { Name = "${include.root.locals.merged.prefix}-${include.root.locals.merged.env}-ec2-vpc-endpoint" }
    },
  }
  tags = merge(
    include.root.locals.custom_tags,
    { VantaDescription : "${include.root.locals.merged.prefix}-${include.root.locals.merged.env}-vpc-endpoints" },
  )
}
```

After upgrading to 0.55.4 I get these error

```
ERRO[0000] Error: Unknown variable
            
ERRO[0000]   on /home/klefevre/git/iac/aws/terragrunt/live/testnet/eu-west-1/eks/vpc/terragrunt.hcl line 33: 
ERRO[0000]   33:   azs  = dependency.datasources.outputs.aws_availability_zones.names 
ERRO[0000]                                              
ERRO[0000] There is no variable named "dependency".
    
ERRO[0000] Error: Unknown variable
            
ERRO[0000]   on /home/klefevre/git/iac/aws/terragrunt/live/testnet/eu-west-1/eks/vpc/terragrunt.hcl line 35: 
ERRO[0000]   35:   public_subnets  = [for k, v in slice(dependency.datasources.outputs.aws_availability_zones.names, 0, 3) : cidrsubnet(local.vpc_cidr, 3, k)] 
ERRO[0000]                                              
ERRO[0000] There is no variable named "dependency".
    
ERRO[0000] Error: Unknown variable
            
ERRO[0000]   on /home/klefevre/git/iac/aws/terragrunt/live/testnet/eu-west-1/eks/vpc/terragrunt.hcl line 36: 
ERRO[0000]   36:   private_subnets = [for k, v in slice(dependency.datasources.outputs.aws_availability_zones.names, 0, 3) : cidrsubnet(local.vpc_cidr, 3, k + 3)] 
ERRO[0000]                                              
ERRO[0000] There is no variable named "dependency".
```

Here is my dependency terragrunt.hcl file:

```
include "root" {
  path           = find_in_parent_folders()
  expose         = true
  merge_strategy = "deep"
}

terraform {
  source = "github.com/terraform-aws-modules/terraform-aws-vpc?ref=v5.5.2"
}

dependency "datasources" {
  config_path = "../../datasources"
}

locals {
  vpc_cidr         = "10.21.0.0/16"
  full_name        = "${include.root.locals.merged.prefix}-${include.root.locals.merged.env}"
  eks_cluster_name = "${include.root.locals.merged.prefix}-${include.root.locals.merged.provider}-${include.root.locals.merged.env}-${include.root.locals.merged.aws_region}"
}

inputs = {

  tags = merge(
    include.root.locals.custom_tags,
    {
      "kubernetes.io/cluster/${local.eks_cluster_name}" = "shared",
      VantaDescription                                  = local.full_name,
    },
  )

  name = local.full_name
  cidr = local.vpc_cidr
  azs  = dependency.datasources.outputs.aws_availability_zones.names

  public_subnets  = [for k, v in slice(dependency.datasources.outputs.aws_availability_zones.names, 0, 3) : cidrsubnet(local.vpc_cidr, 3, k)]
  private_subnets = [for k, v in slice(dependency.datasources.outputs.aws_availability_zones.names, 0, 3) : cidrsubnet(local.vpc_cidr, 3, k + 3)]

  enable_ipv6                                    = true
  public_subnet_ipv6_prefixes                    = [0, 1, 2]
  public_subnet_assign_ipv6_address_on_creation  = true
  private_subnet_ipv6_prefixes                   = [3, 4, 5]
  private_subnet_assign_ipv6_address_on_creation = true

  enable_nat_gateway = true
  single_nat_gateway = true

  manage_default_security_group = true
  map_public_ip_on_launch       = true

  default_security_group_egress = [
    {
      from_port        = 0
      to_port          = 0
      protocol         = "-1"
      cidr_blocks      = "0.0.0.0/0"
      ipv6_cidr_blocks = "::/0"
    }
  ]
  default_security_group_ingress = [
    {
      from_port        = 0
      to_port          = 0
      protocol         = "-1"
      cidr_blocks      = "0.0.0.0/0"
      ipv6_cidr_blocks = "::/0"
    }
  ]

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.eks_cluster_name}" = "shared"
    "kubernetes.io/role/elb"                          = "1"
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.eks_cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"                 = "1"
  }

  enable_flow_log                                 = true
  create_flow_log_cloudwatch_log_group            = true
  create_flow_log_cloudwatch_iam_role             = true
  flow_log_cloudwatch_log_group_retention_in_days = 365
  flow_log_traffic_type                           = "REJECT"
}
```

**Expected behavior**

No errors. But despite the error logs. it does not seem to pose an issue with dependencies

**Versions**
- Terragrunt version: 0.55.4
- Terraform version: 1.6.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): ubuntu 22.04

**Comment by denis256** [comment] 2024-02-22 13:35
Issue happens on https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.6 ?

**Comment by denis256** [comment] 2024-02-22 13:35
Seems to be duplicate of https://github.com/gruntwork-io/terragrunt/issues/2955

**Closed** 2024-02-22 17:50 UTC
Labels: bug
