### ISSUE TITLE
Can parent terraform.tfvars contain environment variables?

### ISSUE THREAD

**Issue by dhoer** [gruntwork-io/terragrunt#137] opened 2017-02-19 03:15 UTC
I can't seem to get the following to work:

```hcl
terragrunt = {
  # Configure Terragrunt to use DynamoDB for locking
  lock {
    backend = "dynamodb"
    config {
      state_file_id = "${path_relative_to_include()}"
    }
  }

  # Configure Terragrunt to automatically store tfstate files in an S3 bucket
  remote_state {
    backend = "s3"
    config {
      encrypt = "true"
      bucket = "mybucket"
      key = "${path_relative_to_include()}/terraform.tfstate"
      region = "us-east-1"
    }
  }
}

region = "us-east-1"
```

```hcl
terragrunt = {
  include {
    path = "${find_in_parent_folders()}"
  }

  terraform {
    source = "../..//modules/app"
  }
}

name = "test"
```
The name variable is available, but the region is not.  Any help on this would be appreciated.

**Comment by brikis98** [comment] 2017-02-19 12:57
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/132. Let's consolidate the discussion in that thread. For the specific answer to your question, see https://github.com/gruntwork-io/terragrunt/issues/132#issuecomment-280848634.

**Closed by brikis98** 2017-02-19 12:57 UTC
