### ISSUE TITLE
Files starting with a . are ignored

### ISSUE THREAD

**Issue by Damy3** [gruntwork-io/terragrunt#1609] opened 2021-03-25 17:07 UTC
I was trying to upload an aws lambda within one of my modules but terragrunt ignores:

- .prettierrc.js
- .eslintrc.js
- .eslintignore

And that makes the deploy script of my lambda fail, is that how it is supposed to be or is it a bug? Maybe I'm just missing a configuration.

Thanks

**Comment by brikis98** [comment] 2021-03-26 08:34
Closing as duplicate of #394.

**Closed by brikis98** 2021-03-26 08:34 UTC
