### ISSUE TITLE
Invalid value for input variable: when input is null

### ISSUE THREAD

**Issue by PePoDev** [gruntwork-io/terragrunt#2076] opened 2022-04-19 08:30 UTC
For example, Use this module 

```hcl
terraform {
  source = "tfr:///terraform-aws-modules/vpc/aws//.?version=3.14.0"
}

inputs = {
  private_subnet_assign_ipv6_address_on_creation = null
}
``` 

```hcl
variable "private_subnet_assign_ipv6_address_on_creation" {
  description = "Assign IPv6 address on private subnet, must be disabled to change IPv6 CIDRs. This is the IPv6 equivalent of map_public_ip_on_launch"
  type        = bool
  default     = null
}
```

```sh
│ Error: Invalid value for input variable
│ 
│ The environment variable
│ TF_VAR_private_subnet_assign_ipv6_address_on_creation does not contain a
│ valid value for variable "private_subnet_assign_ipv6_address_on_creation ":
│ a bool is required.
```

**Comment by yorinasub17** [comment] 2022-04-19 12:41
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/892, which has explanation of why this bug exists (and why it's hard to fix), as well as a suggested workaround.

**Comment by yorinasub17** [comment] 2022-04-19 12:42
Closing as duplicate - please follow #892 for updates on when we tackle/publish a fix for this in terragrunt.

**Closed by yorinasub17** 2022-04-19 12:41 UTC
