### ISSUE TITLE
snap install and git not found

### ISSUE THREAD

**Issue by prees1** [gruntwork-io/terragrunt#260] opened 2017-08-02 22:36 UTC
I installed terragrunt via snap to use on a gitlab ci server. When running terragrunt apply, it runs the Terraform command:

$ terraform init -backend=false -get=false git::ssh://git@github.com/myorg/infrastructure-modules.git?ref=v0.1.1 /tmp/

And it fails with:

Error copying source: error downloading 'ssh://git@github.com/myorg/infrastructure-modules.git?ref=v0.1.1': git must be available and on the PATH

When I uninstall terragrunt with `snap remove terragrunt` and install it manually by putting it on the PATH, terragrunt works as expected.

**Comment by brikis98** [comment] 2017-08-02 22:39
@conorgil, I believe you may have added the `snap` install instructions. Have you seen this issue before or know what could be the cause? Thanks!

**Comment by josh-padnick** [comment] 2017-08-03 17:18
If you look at how [snaps are configured](https://snapcraft.io/), each snap has to define every binary it uses, in this case, including `git`. Unfortunately, I can't easily locate the source code for the terragrunt snap, but I'm guessing that's the issue.

**Comment by brikis98** [comment] 2017-08-03 21:53
Ah, good find. Marking this as a bug. I'd love to know who maintains the snap install and get that fixed.

**Comment by prees1** [comment] 2017-08-03 22:18
Maybe in the interim, a note or warning regarding this on the install page would be useful for people? I'd imagine this is a fairly critical bug?

**Comment by brikis98** [comment] 2017-08-03 22:21
Done! https://github.com/gruntwork-io/terragrunt/commit/64de850c2870cd5c1f2e80fce32777ea81f6a5d0

**Comment by conorgil** [comment] 2017-08-05 01:33
Sorry for delayed response (I haven't had solid internet last few weeks). I did add this to the README, but I just copied it from https://github.com/gruntwork-io/terragrunt/pull/204. Wish I could help, but I haven't actually used snap before.

**Comment by brikis98** [comment] 2017-08-05 11:12
Ah, thanks for the reminder @conorgil!

@popey, do you by any chance maintain the snap installer for Terragrunt?

**Closed** 2018-01-27 00:12 UTC
Labels: bug, help wanted
