### ISSUE TITLE
Unapplied dependency outputs error

### ISSUE THREAD

**Issue by clarklai** [gruntwork-io/terragrunt#914] opened 2019-10-15 22:57 UTC
Terraform v0.20.2

I'm following along with the documentation (https://github.com/gruntwork-io/terragrunt#unapplied-dependency-and-mock-outputs), but seem to keep running into the error:

```
Unsupported attribute; This object does not have an attribute named "platform".
```

I have a pretty straightforward configuration, using ```mock_outputs```, ```mock_outputs_allowed_terraform_commands```, and ```skip_outputs```:

```hcl
# hosting/terragrunt.hcl

terraform {
  source = "${get_terragrunt_dir()}/../../../core/hosting/module"
}

dependency "platform" {
  config_path = "../platform"

  mock_outputs = {
    api_gateway_name = "test_api_gateway_name"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
  skip_outputs = true
}

inputs = {
  api_gateway_name = dependency.platform.outputs.platform
}
```

Project structure:

```
root
├── hosting
│   └── terragrunt.hcl
├── platform
│   └── terragrunt.hcl
└── terragrunt.hcl
```

Is there something I'm missing?

Thanks

**Comment by yorinasub17** [comment] 2019-10-16 01:51
Hi can you share the full log, starting with the command you are running? That context helps a lot for debugging this. Thanks!

**Comment by yorinasub17** [comment] 2019-10-16 01:53
Oh wait, taking a deeper look at the config, I think I spot the problem:

In the inputs, you are referencing:
```
dependency.platform.outputs.platform
```

but in your definition of `mock_outputs`, you don't have a key for `platform`. Should this actually be: `dependency.platform.outputs.api_gateway_name`?

**Comment by clarklai** [comment] 2019-10-16 02:45
Thanks for the response @yorinasub17. You're absolutely right, I misread the documentation - I read it as ```mock_outputs``` keys are to match the keys of the ```inputs``` block. Thanks again for catching that.

**Comment by clarklai** [comment] 2019-10-16 18:46
@yorinasub17 It looks like even after changing the key to ```platform```, the issue persists:

```
Unsupported attribute; This object does not have an attribute named "outputs"
```

Here's the configuration:

```
# hosting/terragrunt.hcl

terraform {
  source = "${get_terragrunt_dir()}/../../../core/hosting/module"
}

dependency "platform" {
  config_path = "../platform"

  mock_outputs = {
    api_gateway_name = "test_api_gateway_name"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
  skip_outputs = true
}

inputs = {
  api_gateway_name = dependency.platform.outputs.api_gateway_name
}
```

**Comment by barryib** [comment] 2019-10-16 19:12
@clarklai what Terragrunt command are you using ? Can you please share the full log as @yorinasub17 suggested ?

**Comment by clarklai** [comment] 2019-10-16 19:18
I resolved the issue. It was because I had ```skip_outputs = true``` in the dependency definition.

**Comment by yorinasub17** [comment] 2019-10-16 20:48
That sounds like a bug, since we introduced the behavior to return the `mock_outputs` when `skip_outputs = true` in [v0.19.29](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.29).

Would you be ok with sharing the logs still so we can investigate this further and make sure there isn't an issue in terragrunt itself?

**Comment by barryib** [comment] 2019-10-16 23:59
From what I understood from the [code](https://github.com/gruntwork-io/terragrunt/blob/master/config/dependency.go#L175-L182), you get this error only when these 2 are true :
-  `skip_outputs` is true => you don't want to pull in states. This can make sense only with the `validate`
- mock_outputs_allowed_terraform_commands doesn't match the Terraform command you're using

In short, if you don't want to read states and don't provide allowed commands, you can't have dependency outputs.

@yorinasub17 @clarklai can we re-open this issue until we make this clair ?

**Comment by clarklai** [comment] 2019-10-17 02:47
I've made some updates to the configuration since my last post, however the issue returns when adding back ```skip_outputs``` to the configuration.

[skip_outputs.log](https://github.com/gruntwork-io/terragrunt/files/3737189/skip_outputs.log)

**Comment by barryib** [comment] 2019-10-17 16:31
```
[terragrunt] 2019/10/16 20:41:25 configstack.MultiError Encountered the following errors:
Cannot process module Module /Users/clark/example/deploy/dev/hosting (excluded: false, dependencies: [/Users/clark/example/deploy/dev/platform, /Users/clark/example/deploy/dev/email]) because one of its dependencies, Module /Users/clark/example/framewo
rk/deploy/dev/email (excluded: false, dependencies: [/Users/clark/example/deploy/dev/platform]), finished with an error: /Users/clark/example/deploy/dev/email/terragrunt.hcl:23,41-49: Unsupported attribute; This object does not have an attribute named "outputs"., and 2 other diagnostic(s)
/Users/clark/example/deploy/dev/email/terragrunt.hcl:23,41-49: Unsupported attribute; This object does not have an attribute named "outputs"., and 2 other diagnostic(s)
```

@clarklai Can you share your `/Users/clark/example/deploy/dev/email/terragrunt.hcl` configuration ?

**Comment by barryib** [comment] 2019-10-21 19:47
@clarklai any news ? Do you still have this issue ?

**Comment by clarklai** [comment] 2019-10-23 17:19
@barryib Here's the configuration for email/terragrunt.hcl:

```
terraform {
  source = "${get_terragrunt_dir()}/../../../core/email/module"
}

include {
  path = find_in_parent_folders()
}

dependency "platform" {
  config_path = "../platform"

  mock_outputs = {
    artifacts_bucket = "mock_artifacts_bucket_name"
    kms_key_id = "mock_kms_key_id"
    sns_dlq_name = "mock_sns_dlq_name"
  }

  mock_outputs_allowed_terraform_commands = ["validate"]
  skip_outputs = true
}

inputs = {
  artifacts_bucket = dependency.platform.outputs.artifacts_bucket
  kms_key_id = dependency.platform.outputs.kms_key_id
  sns_dlq_name = dependency.platform.outputs.sns_dlq_name
  root_dir = "${get_parent_terragrunt_dir()}/../.."
}
```

**Comment by yorinasub17** [comment] 2019-10-23 20:31
Ah the issue is in this line:

> mock_outputs_allowed_terraform_commands = ["validate"]

You are basically telling `terragrunt` that it can only use the `mock_outputs` if it is running `terraform validate`, but in the logs you were running `terraform plan`, so it doesn't read the `mock_outputs`.

You can resolve that particular error by adding `plan` to the list.

**Comment by clarklai** [comment] 2019-10-29 05:57
> You can resolve that particular error by adding `plan` to the list.

@yorinasub17 Yes, adding ```plan``` does remove the error.

However, does this mean that future ```terraform plan``` will continue to use the ```mock_outputs``` after ```terraform apply``` has been ran at least once?

**Comment by yorinasub17** [comment] 2019-10-29 12:26
If you have `skip_outputs = true`, then yes. However, if you remove that line, then it will only use the `mock_outputs` when there are no outputs upstream.

**Comment by yorinasub17** [comment] 2019-10-29 12:26
Going to close this now given that this is intended behavior.

**Closed by yorinasub17** 2019-10-29 12:26 UTC
Labels: needs investigation, question

**Comment by subhash-dream11** [comment] 2021-06-20 14:21
Hey @yorinasub17, I am facing similar issues while adding a new dependency variable in the existing dependency block. `mock_outputs` fails as there is already some output, so didn't pass the default value for the new dependency. 
`include {
  path = find_in_parent_folders()
}

dependency "common_lb" {
  config_path = "../common1"
  mock_outputs = {
    lb_dns = "sample_dns"
    lb_dns2 = "sample_dns" # inserted after successful terragrunt apply
  }
  # for tf validate
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  
}


inputs = {
  common_lb_dns = dependency.common_lb.outputs.lb_dns
  common_lb_dns2 = dependency.common_lb.outputs.lb_dns2 # inserted after successful terragrunt apply
}
`
Is am I missing some configurations? If I add `skip_output=true`, am getting 

` Unsupported attribute; This object does not have an attribute named "outputs"., and 1 other diagnostic(s)`

**Comment by diodfr** [comment] 2021-08-18 14:40
@subhash-dream11 
I think I have been the same issue as your.
This the workflow :
- apply with terragrunt
- add ouput "my_new_output" to a module that already has ouputs
- plan with terragrunt
   + Running command: terraform output -json only shows previous outputs ( "my_new_output"  is absent)
   + terragrunt fails with  This object does not have an attribute named "my_new_output"

**Workaround** => use **mock_outputs_merge_with_state = true** available since terragrunt v0.31.4

**Comment by basarsoker** [comment] 2022-01-29 10:10
Could you give more details? This solves my problem, but I do wonder about the reason behind it.

**Comment by luispabon** [comment] 2022-06-23 10:27
Same issue on terragrunt v0.35.13. When adding new outputs, terragrunt fails with `Unsupported attribute; This object does not have an attribute named "MY_OUTPUT"` unless I add `mock_outputs_merge_with_state = true` to the config

**Comment by DmytroRomantsovM** [comment] 2025-05-07 09:38
The same issue with v.0.78.1.  Adding `mock_outputs_allowed_terraform_commands` didn't resolve it. However, both `plan` and `apply` work fine, just the error in the logs is confusing. 

Code:
```
include {
  path   = "${get_repo_root()}/infrastructure/stack-modules/terragrunt-base-infra.hcl"
  expose = true
}

terraform {
  source = "${get_repo_root()}/infrastructure/stack-modules/modules//irsa"
}

dependency "s3_jira" {
  config_path = "../s3-jira"
  mock_outputs = {
    s3_bucket_arn = "mock_bucket_arn"
  }
  mock_outputs_allowed_terraform_commands = ["init", "plan"]
}

inputs = {
  repository_list = ["repo-name"]

  s3_permissions = [
    {
      bucket_arn         = dependency.s3_jira.outputs.s3_bucket_arn
      enable_irsa_role   = true
      enable_github_role = true
    }]
}
```
Logs:
```
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.78.1
11:30:44.199 DEBUG  Terragrunt Version: 0.78.1
.....
11:30:45.055 DEBUG  Found locals block: evaluating the expressions.
11:30:45.055 DEBUG  Evaluated 7 locals (remaining 9): parent_dir_name, environment, repo_name, service_vars, service_config, current_dir, service_vars_location
11:30:45.056 DEBUG  [../../stack-modules/environments/dev-tools] Found locals block: evaluating the expressions.
11:30:45.056 DEBUG  [../../stack-modules/environments/dev-tools] Evaluated 4 locals (remaining 0): state_dynamodb_table, iam_role, state_bucket, state_region
11:30:45.057 DEBUG  Evaluated 4 locals (remaining 5): dependencies_dir, variant_mappings, environment_vars, customers
11:30:45.057 DEBUG  Evaluated 5 locals (remaining 0): service_name, state_bucket,, state_dynamodb_table, state_region
11:30:45.060 ERROR  Error: Unsupported attribute
11:30:45.060 ERROR    on ./terragrunt.hcl line 23:
11:30:45.060 ERROR    23:       bucket_arn         = dependency.s3_jira.outputs.s3_bucket_arn
11:30:45.060 ERROR  This object does not have an attribute named "s3_jira".
11:30:45.064 DEBUG  Found locals block: evaluating the expressions.
11:30:45.064 DEBUG  Evaluated 7 locals (remaining 9): service_vars_location, repo_name, environment, service_vars, service_config, current_dir, parent_dir_name
11:30:45.065 DEBUG  [../../stack-modules/environments/dev-tools] Found locals block: evaluating the expressions.
11:30:45.065 DEBUG  [../../stack-modules/environments/dev-tools] Evaluated 4 locals (remaining 0): iam_role, state_bucket, state_region, state_dynamodb_table
11:30:45.066 DEBUG  Evaluated 4 locals (remaining 5): dependencies_dir, variant_mappings, environment_vars, customers
11:30:45.067 DEBUG  Included config ../../stack-modules/terragrunt-base-infra.hcl has strategy shallow merge: merging config in (shallow).
11:30:45.068 DEBUG  Complete processing get_working_dir built-in function
11:30:45.072 DEBUG  [../s3-jira] Running command: git rev-parse --show-toplevel
....
1:30:45.179 DEBUG  [../s3-jira] Detected module ../s3-jira/terragrunt.hcl is already init-ed. Retrieving outputs directly from working directory.
11:30:45.179 DEBUG  [../s3-jira] Running command: terraform output -json
11:30:45.179 DEBUG  [../s3-jira] Engine is not enabled, running command directly in ../s3-jira/.terragrunt-cache/WYLbuAYBOoGh7-F1Fwcm3H051uU/XCfXqWnFx6Eopx__MFvYbu1o0h0/s3
11:30:48.246 DEBUG  [../s3-jira] Retrieved output from ../s3-jira/terragrunt.hcl as json: {
  "s3_bucket_arn": {
    "sensitive": false,
    "type": "string",
    "value": "arn:aws:s3:::bucket_name"
  },
  "s3_bucket_domain_name": {
    "sensitive": false,
    "type": "string",
    "value": "bucket_name.s3.amazonaws.com"
  },
  "s3_bucket_id": {
    "sensitive": false,
    "type": "string",
    "value": "bucket_name"
  },
  "s3_bucket_regional_domain_name": {
    "sensitive": false,
    "type": "string",
    "value": "bucket_name.s3.eu-west-1.amazonaws.com"
  }
```
