### ISSUE TITLE
Terraform extra_arguments arguments Ignored

### ISSUE THREAD

**Issue by derekrprice** [gruntwork-io/terragrunt#700] opened 2019-05-09 13:45 UTC
My terragrunt block contains this:

    terraform {
        extra_arguments "custom_vars" {
            commands = ["${get_terraform_commands_that_need_vars()}"]

            arguments = [
                "-var=\"module=${path_relative_to_include()}\""
            ]
        }
    }

When running `terragrunt plan`, I see that module is not defined:

    [terragrunt] 2019/05/09 09:32:31 Running command: terraform plan -var="module=staging/db" -out .tfplan
    var.module
      Enter a value:

Note that the module variable appears to be defined in the command that terragrunt reported that it was running.  In fact, when I copy and paste that terraform command into a shell in the terragrunt cached module, it works just fine, so terragrunt does not appear to be running the same command that it is reporting:

    PS D:\redacted\staging\db\.terragrunt-cache\redacted\shared-app-db> terraform plan -var="module=staging/db" -out .tfplan
    Refreshing Terraform state in-memory prior to plan...
    The refreshed state will be used to calculate this plan, but will not be
    persisted to local or remote state storage.
    ...
    ------------------------------------------------------------------------

    No changes. Infrastructure is up-to-date.

    This means that Terraform did not detect any differences between your
    configuration and real physical resources that exist. As a result, no
    actions need to be performed.

When I also define optional_var_files in the same block, those work fine, so this appears to be specific to arguments (-var and -var-file arguments appear in the command that terragrunt reports that it will run, but only the -var-file arguments appear to be processed by terraform, not the -var).

**Comment by brikis98** [comment] 2019-05-10 23:18
You have the wrong syntax for `arguments`.

Try:

```hcl
      arguments = [
        "-var", "module=${path_relative_to_include()}"
      ]
```

**Comment by derekrprice** [comment] 2019-05-13 12:16
@brikis98, that worked, though it still seems odd that the echoed command works when copy and pasted.  Anyhow, I'll close this issue.  Thanks.

**Comment by derekrprice** [comment] 2019-05-13 16:36
@brikis98, turns out that that wasn't a complete work-around.  It worked fine for `terragrunt plan -out .tfplan`, but when I attempted to apply the plan file via `terragrunt apply .tfplan`, I got an error:

    [terragrunt] 2019/05/13 12:12:38 Running command: terraform apply module=test/db .tfplan
    Too many command line arguments. Configuration path expected.
    [terragrunt] 2019/05/13 12:12:38 Hit multiple errors:
    exit status 1

Note that the second item from the arguments array appears to be applied on the command line reported by terragrunt (`module=test/db`), without the first (`-var`).

Removing the escaped quotes from my original specification appears to work for both plan and apply:

    arguments = [
        "-var=module=${path_relative_to_include()}"
    ]
 
Anyhow, despite having a workaround, this certainly seems non-obvious.  I'm thinking that both the escaped quotes and the multiple arguments syntax should have worked.

**Comment by brikis98** [comment] 2019-05-14 09:38
I think that's a different issue, which is a duplicate of https://github.com/gruntwork-io/terragrunt/issues/454.

**Closed by brikis98** 2019-05-14 09:38 UTC
Labels: question

**Comment by derekrprice** [comment] 2019-05-14 10:34
That issue appears to be about ordering arguments. This one is about "commands" being ignored for extra_arguments after the first. How are they related?

**Comment by brikis98** [comment] 2019-05-15 11:38
I could be wrong, but I suspect this is also an argument ordering issue.
