### ISSUE TITLE
Option for TERRAGRUNT_SOURCE to override only base path (before `//`)

### ISSUE THREAD

**Issue by max-lobur** [gruntwork-io/terragrunt#1139] opened 2020-04-15 18:24 UTC
When switching between local (TERRAGRUNT_SOURCE) and git-based runs we often fall into issue where `source` link in code got broken, stale or similar. Would be great to be able to override only path before `//`, then if your `source` link in code doesn't match the refactored modules repo structure you notice this immediately.

Not sure about `?ref=` tho, maybe simply ignore it if source override is set to local dir instead of git url

**Comment by WigglesMcMuffin** [comment] 2020-04-20 17:07
We use `plan-all` every time, which makes it so that we always pull dependencies into the plan, and also everything after the `//` is ignored.

**Comment by brikis98** [comment] 2020-04-27 10:00
Yes, Terragrunt is a bit inconsistent with `--terragrunt-source` in `xxx-all` vs `xxx` commands. Closing as duplicate of #1138, which has a proposed improvement.

**Closed by brikis98** 2020-04-27 10:00 UTC
