### ISSUE TITLE
Newest version (v0.45.9) contains a space

### ISSUE THREAD

**Issue by IvaGelev-TomTom** [gruntwork-io/terragrunt#2556] opened 2023-05-05 13:49 UTC
In out terragrunt config, we're using 'latest' for the version, but with the latest one being retrieved, there's a leading space: 
'Action failed with "Error: Failed to download Terragrunt from https://github.com/gruntwork-io/terragrunt/releases/download/ v0.45.9/terragrunt_linux_amd64" ' causing download failure.

To reproduce, just use 'latest' for the version.

Expected behavior:
There's no space in front of the version, so the url is created correctly.

**Comment by j-hannes** [comment] 2023-05-05 15:34
Same on our project:
![image](https://user-images.githubusercontent.com/1204339/236502727-2e894301-8c00-4684-bdaa-e0ddd2666039.png)

**Comment by abower-digimarc** [comment] 2023-05-05 16:07
Same issue. Breaks any attempt to download latest.

**Comment by Kikivsantos** [comment] 2023-05-05 19:21
Same error here. Something was changed and this is breaking our delivery =/


[INFO] TerragruntVersion: latest
[INFO] Setting up Terragrunt version: 'latest'
[INFO] Latest Terragrunt version: ' v0.4[5](https://github.com/tag-trade-repository/mongodb-atlas-automation/actions/runs/4894999452/jobs/8743860559#step:5:6).9'
[INFO] Downloading from: 'https://github.com/gruntwork-io/terragrunt/releases/download/ v0.45.9/terragrunt_linux_amd[6](https://github.com/tag-trade-repository/mongodb-atlas-automation/actions/runs/4894999452/jobs/8743860559#step:5:7)4'
Error: Action failed with "Error: Failed to download Terragrunt from  https://github.com/gruntwork-io/terragrunt/releases/download/ v0.45.9/terragrunt_linux_amd64"

**Comment by denis256** [comment] 2023-05-05 20:47
Hi,
can be checked if the issue is fixed now? I updated tag name of release

**Comment by denis256** [comment] 2023-05-05 20:50
```
$ tgenv install latest
[INFO] Installing Terragrunt v0.45.9
[INFO] Downloading release tarball from https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.9/terragrunt_linux_amd64
############################################################################################################################################################################################################ 100.0%
[INFO] Installation of terragrunt v0.45.9 successful
[INFO] Switching to v0.45.9
[INFO] Switching completed
```

**Comment by IvaGelev-TomTom** [comment] 2023-05-08 09:50
Works for us now

**Closed** 2023-05-08 12:10 UTC
Labels: bug
