### ISSUE TITLE
postpone check for configured backend after init hook is executed

### ISSUE THREAD

**Issue by mariux** [gruntwork-io/terragrunt#785] opened 2019-07-13 21:13 UTC
**Change-Request:** 
Postpone check for `checkTerraformCodeDefinesBackend()` after `before_hook`s are run.

I guess it makes sense to run a `before_hook` before deciding how to actually execute the`terraform` command because executing a before hook might change the situation inside the cache directory.

**Background/Use-Case/Motivation:**
I want to stay DRY in terms of backend configuration so we are actually defining it once at top level of the repository along with the terragrunt.hcl top-level file - as we want to use the same backend for the full repository anyway.

```
  before_hook "copy_backend_before_init" {
    commands = [ "init" ]
    execute  = [ "cp", "-v", "${get_terragrunt_dir()}/${find_in_parent_folders("backend.tf")}", "." ]
  }
```

this fails because `checkTerraformCodeDefinesBackend` is run before `terraform init` and before `before_hook` for init is executed.

https://github.com/gruntwork-io/terragrunt/blob/2fe4b90a6ece8f21c448657cb9de928e5a8b23dc/cli/cli_app.go#L287

error I run into:

```
[terragrunt] 2019/07/13 22:24:44 Found remote_state settings in /home/[...]/terragrunt.hcl but no backend block in the Terraform code in /home/[...]/.terragrunt-cache/rpSgVm5WzqsJDKJ70EGvpZ9ZxXw/A35GeYiqYDYXDWZftKtd1kkU5ic. 
   You must define a backend block (it can be empty!) in your Terraform code or your remote state settings will have no effect! It should look something like this:

terraform {
  backend "s3" {}
}
```

`backend.tf` in top-level directory is (which we have to copy to every module atm (?)):
```
terraform {
  backend "s3" {}
  required_version = ">= 0.12.0"
}
```
I also tried to use the `init-from-module` hook but this one is not executed in the cache directory so I can only use it as a workaround (before: copy to current dir, after init: delete form terragrunt dir) which works now, but is kind of hacky.

**Comment by lorengordon** [comment] 2019-07-13 22:35
This is basically a duplicate of https://github.com/gruntwork-io/terragrunt/issues/749...

Or at least, if init-from-module were operating out of the cache dir as it did before, the described use case would still work as it did before. :/

**Comment by brikis98** [comment] 2019-07-18 15:38
If #749 is fixed, would that fix this issue? If so, we can close this one as a dupe.

**Comment by mariux** [comment] 2019-07-21 16:37
as far as i get it, fixing #749 would just enable a second work around for the issue.

current flow seems to be:
1) run checks to validate terraform execution environment is okay (e.g. check for backend config present)
2) run before_hook
3) run terraform
4) run after_hook

what would make more sense might be switching 1 and 2
1) run before hook (creates backend config)
2) validate environment before running terraform (would succeed now)
3) run terraform
4) run after_hook

No matter where the hooks are executed. concrete use case is not to run `checkTerraformCodeDefinesBackend` before the `before_hook` has been executed (but after).

**Comment by antonbabenko** [comment] 2019-09-06 13:19
I think I agree with what @mariux is saying, but I also wonder how other people are solving this breaking change between 0.18 and 0.19?

**Comment by lorengordon** [comment] 2020-02-17 05:24
The new `terragrunt-read-config` after hook might help with this use case...?

* https://github.com/gruntwork-io/terragrunt/pull/1030

**Comment by mariux** [comment] 2020-02-17 11:28
we will upgrade and give feedback asap. thx for the work done.

**Comment by mariux** [comment] 2020-02-17 19:10
first accidentally tried with before hook which failed... but after reading again i saw it's a after hook and this actually works like a charm and fixes the issue described above...

```
  after_hook "copy_backend" {
    commands = [
      "terragrunt-read-config"
    ]
    execute = .....
```

:heart:  thank you for fixing/enabling this. closing ticket.

**Comment by mariux** [comment] 2020-02-17 19:31
sorry, partied too early... :
> I also tried to use the init-from-module hook but this one is not executed in the cache directory so I can only use it as a workaround (before: copy to current dir, after init: delete form terragrunt dir) which works now, but is kind of hacky.

this is also true for the new hook... it is not executed in the cache directory and would need the same hacky workaround of removing files afterwards.

**Comment by yorinasub17** [comment] 2020-02-18 02:03
We just released https://github.com/gruntwork-io/terragrunt/releases/tag/v0.22.0, which I believe will address your use case (let us know if it doesn't!). See [the updated docs](https://terragrunt.gruntwork.io/docs/features/keep-your-remote-state-configuration-dry/#using-the-generate-property-to-generate-terraform-code-for-managing-remote-state) for more info.

**Comment by everops-kevin** [comment] 2020-04-14 21:56
I ran into the issue OP describes and was able to solve it using `generate` in my top-level terragrunt.hcl's `remote_state` block!

**Comment by yorinasub17** [comment] 2020-10-13 15:27
Closing this as I believe the `generate` approach will fully solve this problem. If there is a need for additional features, please open a new issue.

Thanks everyone for the feedback and use cases!

**Closed by yorinasub17** 2020-10-13 15:27 UTC
Labels: enhancement, help wanted
