### ISSUE TITLE
Dependency fetching seems incredibly slow; one dependency adds 20+ seconds to 'terragrunt plan' execution time.

### ISSUE THREAD

**Issue by TonyLovesDevOps** [gruntwork-io/terragrunt#1438] opened 2020-11-24 20:49 UTC
First of all: thanks for creating `terragrunt`! Both this tool and the articles from @brikis98 have significantly contributed to the enjoyment and success of my DevOps vocation.

That said, I (finally) just started using module dependencies and they seem to work as intended, yay! However, the *time* it adds to running `terragrunt plan` is making my workflow sad. Before setting up this module dependency, the time delta between executing `terragrunt plan` and getting to the point where `terragrunt` shows `Running command: terraform plan` was ~2 seconds. Now it's 20+ seconds! Is this expected?

We have what is (I think?) a simple dependency setup. Service/module names changes to protect ~~the innocent~~ my pride.
```
├─ service-one/
│  ├─ terragrunt.hcl
│  └─ main.tf
├─ service-two/
│  ├─ terragrunt.hcl
│  └─ main.tf
└─ modules/
   └─ a-module/
   │  └─ main.tf
   └─ b-module/
      └─ main.tf
```

* `service-one` pulls in `a-module`.
* `service-two` pulls in `b-module`.
* `service-two` takes input variables from `service-two` via this `terragrunt.hcl` stanza:
```
dependency "service-one" {
  config_path = "../service-one"
}

inputs = {
  foo = dependency.service-one.outputs.foo
  bar = dependency.service-one.outputs.bar
  baz = dependency.service-one.outputs.baz
}
```

Somehow this takes 20+ (sometimes over 30) seconds:

```
$ terragrunt plan -out plan.out
[terragrunt] [/Users/myname/git/infrastructure/terraform/service-two] 2020/11/24 13:13:38 Running command: terraform --version
[terragrunt] 2020/11/24 13:13:38 Terraform version: 0.13.5
[terragrunt] 2020/11/24 13:13:38 Reading Terragrunt config file at /Users/myname/git/infrastructure/terraform/service-two/terragrunt.hcl
[terragrunt] [/Users/myname/git/infrastructure/terraform/service-one] 2020/11/24 13:13:38 Generated file /Users/myname/git/infrastructure/terraform/service-one/.terragrunt-cache/016418505/backend.tf.
[terragrunt] [/Users/myname/git/infrastructure/terraform/service-one] 2020/11/24 13:13:38 Running command: terraform init -get=false -get-plugins=false
[terragrunt] [/Users/myname/git/infrastructure/terraform/service-one] 2020/11/24 13:14:01 Running command: terraform output -json
[terragrunt] 2020/11/24 13:14:05 Running command: terraform plan -out plan.out

```

Based on this output, it looks like the `terraform init -get=false -get-plugins=false` command is what's taking so long. However, when I manually run this same command in the `service-one` directory, it takes < 5 seconds.

**Comment by yorinasub17** [comment] 2020-11-24 21:12
This is essentially a duplicate of https://github.com/gruntwork-io/terragrunt/issues/1322. You can follow that ticket for updates on when we improve this.

As far as workarounds go, depending on how deep your dependencies are, it may be faster to go through the standard path (set `disable_dependency_optimization = false` on your remote state block).

**Closed by yorinasub17** 2020-11-24 21:12 UTC

**Comment by TonyLovesDevOps** [comment] 2020-11-25 20:15
I've subscribed to #1322, though I will add here that setting `disable_dependency_optimization = false` _does not_ appear to affect the timings at all in my setup.
