### ISSUE TITLE
inconsistent apply and destroy with ci

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#376] opened 2017-11-16 18:53 UTC
I have a ci job that applies a plan in a disposable env (1:1 with my feature branches). When I am done with the code review I have another ci job that destroys the plan. The destroy job fails and is looking for a file that does not exist.

- auto-init is not disabled 
- there are no artifacts shared between the two jobs
- both jobs use the same s3/dyndb  remote backend as configured by terragrunt

The apply cmd:
```
terragrunt apply --terragrunt-working-dir config/stage/aws
```

The failing destroy cmd:
```
$ terragrunt destroy --terragrunt-non-interactive --terragrunt-working-dir config/stage/aws
[terragrunt] [/builds/tom.davidson/devops-k8s] 2017/11/16 17:38:38 Running command: terraform --version
[terragrunt] 2017/11/16 17:38:38 Reading Terragrunt config file at /builds/tom.davidson/devops-k8s/terraform.tfvars
[terragrunt] 2017/11/16 17:38:38 *os.PathError Error reading file at path /builds/tom.davidson/devops-k8s/terraform.tfvars: open /builds/tom.davidson/devops-k8s/terraform.tfvars: no such file or directory
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/errors/errors.go:26 (0x462c3c)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/util/file.go:128 (0x4663ea)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config.go:188 (0x491e07)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config.go:178 (0x491d37)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:202 (0x45c6cf)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:196 (0x45c670)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:177 (0x45c35c)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:502 (0x49ca94)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:268 (0x49a7cd)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/main.go:20 (0x4010c4)
/usr/local/go/src/runtime/proc.go:183 (0x42a864)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x458e51)

[terragrunt] 2017/11/16 17:38:38 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

The config dir structure:
```
config/
├── common.tfvars
├── pq
│   └── terraform.tfvars
├── prod
│   ├── hactar
│   │   ├── main.tf
│   │   └── terraform.tfvars
│   └── roosta
│       ├── main.tf
│       └── terraform.tfvars
├── stage
│   ├── aws
│   │   └── terraform.tfvars
│   ├── stage.tfvars
│   └── vmw
│       ├── main.tf
│       └── terraform.tfvars
└── terraform.tfvars
```

**Comment by brikis98** [comment] 2017-11-16 23:27
Why is it looking in `/builds/tom.davidson/devops-k8s/terraform.tfvars` if you're pointing it at `config/stage/aws`?

**Comment by tomdavidson** [comment] 2017-11-17 00:06
that's what I thought :D

here is config/terraform.tfvars:
```hcl
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket         = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
      key            = "tf-state/${path_relative_to_include()}/terraform.tfstate"
      region         = "${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}"
      encrypt        = true
      dynamodb_table = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
    }
  }

  terraform {

    extra_arguments "vars" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      required_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("common.tfvars")}"
      ]

      optional_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("stage.tfvars", "skip-if-stage.tfvars-does-not-exist")}"
      ]

    }
  }
}
``

And the config/stage/aws/terraform.tfvars:

```hcl
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket         = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
      key            = "tf-state/${path_relative_to_include()}/terraform.tfstate"
      region         = "${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}"
      encrypt        = true
      dynamodb_table = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
    }
  }

  terraform {

    extra_arguments "vars" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      required_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("common.tfvars")}"
      ]

      optional_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("stage.tfvars", "skip-if-stage.tfvars-does-not-exist")}"
      ]

    }
  }
}
```

**Comment by brikis98** [comment] 2017-11-17 11:26
Ah, I see what's happening. This is a bug where Terragrunt is ignoring the `--terragrunt-working-dir` param when looking for a `terraform.tfvars` file. It's a duplicate of #315 (see https://github.com/gruntwork-io/terragrunt/issues/315#issuecomment-336190690 for context).

**Comment by brikis98** [comment] 2017-11-17 11:27
Oh, and the workaround for now is to *also* explicitly (and a bit redundantly) specify the config file to load using the `--terragrunt-config` flag.

**Closed by brikis98** 2017-11-17 11:26 UTC

**Comment by tomdavidson** [comment] 2017-11-17 12:24
I wonder why tg ignores the --terragrunt-working-dir in my ci job but I can run the same command locally and it is not ignored.

Would changing directories rather than using the --terragrunt-working-dir  flag work around the issue or would that present other side-effects?

**Comment by brikis98** [comment] 2017-11-17 12:25
Changing dirs would work fine.

**Comment by tomdavidson** [comment] 2017-11-17 15:26
shucks, not quite, i loose all of my common config on the copy job:

```
...
[terragrunt] 2017/11/17 15:17:51 Copying files from /builds/tom.davidson/devops-k8s/config/stage/aws into /runner/.terragrunt/6XEZOZTdvjPmqpWCl7fjVGY6etg/M7u2ZJYTa7o8pBsG8-zREbJ95No/k8s/aws
...
Failed to load Terraform configuration or plan: open : no such file or directory

``

Which config do I need to specify with --terragrunt-config? the root one with the backend config?
