### ISSUE TITLE
Error occuring when trying to run `init` with Terraform 0.13

### ISSUE THREAD

**Issue by cwoolum** [gruntwork-io/terragrunt#1299] opened 2020-08-14 14:38 UTC
When I try to run init with 0.13, it is unable to restore the providers. From the errors, it seems to be a relative path issue. This is on windows. My Linux env is borked right now so I'm unable to test there.

```
Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of -/azurerm...
- Finding latest version of -/random...
- Finding hashicorp/azurerm versions matching "2.23.0, >= 2.5.0"...
- Finding hashicorp/azuread versions matching "~> 0.7.0"...
- Finding latest version of -/azuread...
- Installing -/azuread v0.11.0...
- Installed -/azuread v0.11.0 (signed by HashiCorp)
- Installing -/azurerm v2.23.0...
- Installed -/azurerm v2.23.0 (signed by HashiCorp)
- Installing -/random v2.3.0...
- Installed -/random v2.3.0 (signed by HashiCorp)
- Installing hashicorp/azurerm v2.23.0...
- Installing hashicorp/azuread v0.7.0...

Error: Failed to install provider

Error while installing hashicorp/azurerm v2.23.0: open
.terraform\plugins\registry.terraform.io\hashicorp\azurerm\2.23.0\windows_amd64\terraform-provider-azurerm_v2.23.0_x5.exe:
The system cannot find the path specified.


Error: Failed to install provider

Error while installing hashicorp/azuread v0.7.0: open
.terraform\plugins\registry.terraform.io\hashicorp\azuread\0.7.0\windows_amd64\terraform-provider-azuread_v0.7.0_x4.exe:
The system cannot find the path specified.

[terragrunt] 2020/08/14 07:29:58 Hit multiple errors:
exit status 1
```

Everything is working correctly in a pure Terraform environment.

terragrunt version `v0.23.32`

**Comment by yorinasub17** [comment] 2020-08-14 18:16
I think this is running into the long path issue. There is a suggested fix here: https://github.com/gruntwork-io/terragrunt/issues/581#issuecomment-460051767

**Comment by Ettery** [comment] 2020-11-19 11:43
Also had this problem, fought with it for hours, and it was the Windows path length limitation.  Check out Issue #581 for workarounds.

**Comment by brikis98** [comment] 2021-02-25 10:25
Closing as duplicate of #581.

**Closed by brikis98** 2021-02-25 10:25 UTC
Labels: question
