### ISSUE TITLE
Parse terraform variables present in included .tfvars files

### ISSUE THREAD

**Issue by JohnEmhoff** [gruntwork-io/terragrunt#134] opened 2017-02-18 03:09 UTC
It seems only the `terragrunt` section is actually parsed in included .tfvars files. It'd be nice to be able to store environment wide configuration here as well.

**Comment by brikis98** [comment] 2017-02-18 13:19
Duplicate of #132. Let's consolidate the discussion to that issue, since it was filed first.

**Closed by brikis98** 2017-02-18 13:19 UTC
