### ISSUE TITLE
unexpected signal during runtime execution

### ISSUE THREAD

**Issue by jdubeau123** [gruntwork-io/terragrunt#68] opened 2016-12-06 20:50 UTC
terragrunt version: v0.5.1

This is a possible duplicate of https://github.com/gruntwork-io/terragrunt/issues/41, but I get errors that look like this on a fairly regular basis.  Any chance someone can confirm this as a duplicate, or even better provider a fix?

https://gist.github.com/jdubeau123/6f5286fd43019bf66b71ca62e5a0cafe

**Comment by brikis98** [comment] 2016-12-06 21:20
Sorry for the issue. I'm not sure if this is a dupe of #41, but it's no less mysterious. It looks like the `Printf` function is throwing a `panic` on [this line](https://github.com/gruntwork-io/terragrunt/blob/v0.5.1/shell/run_shell_cmd.go#L14):

```go
util.Logger.Printf("Running command: %s %s", command, strings.Join(args, " "))
```

`command` is a `string`. `args` is a `...string` (array). Neither is `nil`. This may be a bug in Go.

**Comment by brikis98** [comment] 2016-12-07 03:52
I posted a question on the go-nuts mailing list asking for help: https://groups.google.com/d/msg/golang-nuts/4OJz3jprF84/c8BdI0bkCwAJ

**Comment by josh-padnick** [comment] 2016-12-20 03:45
We believe we've found the culprit: https://golang.org/doc/go1.7#ports:

> Go 1.7 adds support for macOS 10.12 Sierra. Binaries built with versions of Go before 1.7 will not work correctly on Sierra.

If you're subscribed to this thread and NOT on MacOS 10.12 Sierra, please let us know. We'll update the CircleCI builds to use a more recent version of Golang soon.

**Comment by brikis98** [comment] 2016-12-20 20:06
OK, it looks like the most likely explanation for this issue is that our CI job was building binaries with Go 1.6.x, and apparently, those binaries will [not work with the latest version of OS X](https://golang.org/doc/go1.7#ports). I'm not on the latest OS X yet, which explains why I haven't seen these crashes!

We just updated the CI job to use Go 1.7.3. I've cut a new release and the binaries for it should be there in a few minutes: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.7.0. Please try it out and let me know if it works better for you!

**Closed by brikis98** 2016-12-20 20:06 UTC
Labels: bug, help wanted

**Comment by jdubeau123** [comment] 2016-12-20 21:11
Ran a terragrunt operation 100 times in a loop with no crash, looks good.  Thanks!
