### ISSUE TITLE
No way to escape ${ in terragrunt configuration file

### ISSUE THREAD

**Issue by andresvia** [gruntwork-io/terragrunt#564] opened 2018-09-12 07:13 UTC
Assuming `terraform.tfvars` is *the* Terragrunt configuration file, I was not able to find any way to pass variables values containing `${` (the expected escape sequence `$${` doesn't work). In the repro bellow my last resort was to octal escape the dollar sign:

terraform code (`main.tf`)

```
variable "var1" {}
resource "random_pet" "pet" {
  prefix = "${data.template_file.a_template.rendered}-"
}
data "template_file" "a_template" {
  template = "${var.var1}"
  vars {
    text = "replacement"
  }
}
```

Terragrunt configuration (`terraform.tfvars`)

```
terragrunt {
  terraform {
    source = "./"
  }
}
var1 = "\044{text}" // "${text}" fails with [terragrunt] 2018/09/12 00:12:09 Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${text}'
```

Maybe related to: #466

**Comment by brikis98** [comment] 2018-09-12 11:28
Duplicate of #544. Terragrunt uses an ugly regex to process interpolations and escapes and comments don't work properly Will hopefully be fixed when we update to to HCL2 in #466.

**Closed by brikis98** 2018-09-12 11:28 UTC
