### ISSUE TITLE
Dependencies on destroy-all

### ISSUE THREAD

**Issue by bwagnertrc** [gruntwork-io/terragrunt#765] opened 2019-06-26 09:21 UTC
Hi there,

I've been thinking quite a lot about this and I believe the order of dependency evaluation when running terragrunt destroy-all is wrong.
Let's say we have the following directory structure. My use case is kubernetes on AWS, but it doesn't really matter because it should replicate to any situation where I want to use apply-all/destroy-all in subdirectories.

|-| aws
|-|-| Module A
|-| kubernetes
|-|-| namespace_1
|-|-|-| Module B (depends on A)
|-|-|-| Module C (depends on B)
|-|-| namespace_2
|-|-|-| ...

When I am in the namespace_1 folder and run terragrunt apply-all, it will resolve dependencies and make sure that A is created first (or already), then B, then C. However, when running terragrunt destroy-all in the same directory, terragrunt prompts me whether to destroy A as well, which I find awkward because A does not depends on B or C.
The problem becomes even more striking when switching to module B's folder and running terragrunt destroy-all. This time, terragrunt wants to destroy B and A, but not C. Since module C depends on module B and I am going to destroy the latter one, I want to make sure C is properly destroyed as well.

In shorter terms, I believe the dependency graph should be inverted for destroy-all compared to apply-all.

I am aware that I am free to reject applying/destroying individual modules in the prompts and some of my problems are solved by using the --terragrunt-ignore-external-dependencies flag. This is more of a general issue. 

Any thoughts?

Benjamin

**Comment by brikis98** [comment] 2019-06-28 15:06
I don't think it's a question of inverting the dependency graph, as the order that `destroy` happens in is correct. I believe it's more of a question of how Terragrunt discovers and prompts you about dependencies (e.g., see https://github.com/gruntwork-io/terragrunt/issues/272 and https://github.com/gruntwork-io/terragrunt/issues/524). Those needs improvement without a doubt, as the current behavior does not work properly in all circumstances.

**Comment by yorinasub17** [comment] 2021-09-27 18:24
Closing as duplicate of #272. If there is a different feature request here not captured by #272, please open a new issue. Thanks!

**Closed by yorinasub17** 2021-09-27 18:24 UTC
Labels: question
