### ISSUE TITLE
Skip flag behaviour of v0.68.0 breaks project structures

### ISSUE THREAD

**Issue by perplexa** [gruntwork-io/terragrunt#3469] opened 2024-10-11 09:35 UTC
## Describe the bug

v0.68.0 behaviour around merging `skip` breaks project structures.

We have fairly large projects with a significant number of `terragrunt.hcl` files, which all include a parent `terragrunt.hcl` that defines common providers, backend, and locals.

The parent `terragrunt.hcl` should not be applied from run-all, thus it includes a `skip = true` directive. This now gets merged into every other `terragrunt.hcl` file and prevents these from getting applied unless we add `skip = false` to every individual file.

## Steps To Reproduce

Have a parent `terragrunt.hcl` with `skip = true` included like shown below will cause the file that includes it to be skipped as well unless `skip = false` is explicitly added.

```
include "parent" {
  path           = find_in_parent_folders()
  expose         = true
  merge_strategy = "deep"
}
```

## Expected behavior

v0.67.x behaviour

## Versions

- Terragrunt version: v0.68.0
- OpenTofu/Terraform version: v1.9.7

**Comment by rodrigorfk** [comment] 2024-10-11 09:54
Hi @perplexa.

I had the same problem in my organization when using `run-all` for a large fleet of modules, the simpler way to fix this and avoid using the `skip` flag in your parent include, is to just name that file with a different name than `terragrunt.hcl`, for instance `terragrunt-parent.hcl`.

The folder structure would become the following:
```sh
infrastructure/
├── terragrunt-parent.hcl
├── module-1/
│   ├── terragrunt.hcl
├── module-2/
│   ├── terragrunt.hcl
├── module-3/
│   ├── terragrunt.hcl
└── ...
```

And in your `module-x/terragrunt.hcl`, you would have the following: 
```
include "parent" {
  path           = find_in_parent_folders("terragrunt-parent.hcl")
  expose         = true
  merge_strategy = "deep"
}
```

With this strategy, you can execute `terragrunt run-all` from the `infrastructure` folder, without working of terragrunt assuming that parent file as a fully flagged module, avoiding any issue with terragrunt >= `0.68.0`

**Comment by yhakbar** [comment] 2024-10-15 14:55
Other solutions include running `terragrunt run-all` from the same working directory as the parent `terragrunt.hcl` file, or including a [terragrunt-exclude-dir](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-exclude-dir) to avoid picking it up.

Given that this is expected behavior, not a bug, I'm closing this issue out. Please feel free to continue discussions here if more conversation about workarounds is warranted.

**Closed by yhakbar** 2024-10-15 14:55 UTC
Labels: bug

**Comment by lorengordon** [comment] 2024-10-15 16:01
for reference, here's the "issue" where the change was discussed, along with the described use case. fwiw, i also find the change to be quite confusing, and now have to rethink how i was planning to use the `skip` argument.
