### ISSUE TITLE
tfvars not copied if working directory begins with "."

### ISSUE THREAD

**Issue by skluck** [gruntwork-io/terragrunt#475] opened 2018-05-08 14:09 UTC
Ran into this when setting up a CI toolchain. We use the standard directory structure, but move an env into an "artifact" directory which is then bundled up during the build stage. This way regardless of environment, we can bundle the same output directory to be used during the apply/deploy stage.

It looks like terragrunt validates the tfvars fine when they are in the working directory, but fails to copy them over to the temp directory if the working directory begins with dot (`.`). This causes a semi-silent failure because it will essentially run terraform with no tfvars, so projects would receive the defaults (or terraform would prompt for input).

Example:

```
- staging
    - extra.auto.tfvars
    - terraform.tfvars
- prod
    - extra.auto.tfvars
    - terraform.tfvars
```

Build artifact (created during CI build)
```
- .artifact
    - extra.auto.tfvars
    - terraform.tfvars
    - terraform.tfplan     [ created by terragrunt during build ]
```

This artifact/temp directory was `.artifact` so it (hopefully) wouldn't collide with any other directory a project used. But it looks like Terragrunt doesn't copy any files that are contained within a hidden directory.

I added a few hooks to my config to check the files in each directory.

---

Output (Does not properly copy files)

```
> cd .artifact && pwd
/build/.artifact

> terragrunt plan \
    --terragrunt-non-interactive \
    -out="$(pwd)/terraform.tfplan"

[terragrunt] [/build/.artifact] 2018/05/08 13:23:48 Running command: terraform --version
[terragrunt] 2018/05/08 13:23:48 Reading Terragrunt config file at /build/.artifact/terraform.tfvars
[terragrunt] 2018/05/08 13:23:48 Downloading Terraform configurations from git::https://ghe.example.com/terraform/hello-world.git?ref=master into /root/.terragrunt/YqHYO-Q5iIjV7RlR8rIG3covSc0/MiQ5A_dvB0remey-dounjZgYyi4 using terraform init

[terragrunt] [/build/.artifact] 2018/05/08 13:23:48 Initializing remote state for the local backend
[terragrunt] [/build/.artifact] 2018/05/08 13:23:48 Detected 2 Hooks
[terragrunt] [/build/.artifact] 2018/05/08 13:23:48 Running command: terraform init -from-module=git::https://ghe.example.com/terraform/hello-world.git?ref=master /root/.terragrunt/YqHYO-Q5iIjV7RlR8rIG3covSc0/MiQ5A_dvB0remey-dounjZgYyi4

[terragrunt] 2018/05/08 13:24:13 Copying files from /build/.artifact into /root/.terragrunt/YqHYO-Q5iIjV7RlR8rIG3covSc0/MiQ5A_dvB0remey-dounjZgYyi4
[terragrunt] 2018/05/08 13:24:13 Setting working directory to /root/.terragrunt/YqHYO-Q5iIjV7RlR8rIG3covSc0/MiQ5A_dvB0remey-dounjZgYyi4
[terragrunt] 2018/05/08 13:24:13 Detected 2 Hooks

[terragrunt] 2018/05/08 13:24:13 Executing hook: before_hook_0
[terragrunt] 2018/05/08 13:24:13 Running command: ls -hal /build/.artifact
total 20K
drwxr-xr-x 2 root root 4.0K May  8 13:23 .
drwxr-xr-x 5 root root 4.0K May  8 13:23 ..
-rw-r--r-- 1 root root 1003 May  8 13:23 extra.auto.tfvars
-rw-r--r-- 1 root root  568 May  8 13:23 terraform.tfvars

[terragrunt] 2018/05/08 13:24:13 Executing hook: before_hook_1
[terragrunt] 2018/05/08 13:24:13 Running command: ls -hal
total 52K
drwxr-xr-x 6 root root 4.0K May  8 13:24 .
drwxr-xr-x 3 root root 4.0K May  8 13:23 ..
drwxr-xr-x 4 root root 4.0K May  8 13:23 .terraform
-rw-r----- 1 root root   27 May  8 13:24 .terragrunt-source-version
-rw-r--r-- 1 root root 3.1K May  8 13:23 README.md
-rw-r--r-- 1 root root 4.0K May  8 13:23 main.tf
-rw-r--r-- 1 root root  749 May  8 13:23 outputs.tf
-rw-r--r-- 1 root root 3.6K May  8 13:23 variables.tf
[terragrunt] 2018/05/08 13:24:13 Running command: terraform plan -out=/build/.artifact/terraform.tfplan

<< Terraform Asks for missing variables >>
```

Switching from `.artifact` to `artifact` for the working directory works fine:

```
> cd .artifact && pwd
/build/artifact

> terragrunt plan \
    --terragrunt-non-interactive \
    -out="$(pwd)/terraform.tfplan"

[terragrunt] [/build/artifact] 2018/05/08 13:55:56 Running command: terraform --version
[terragrunt] 2018/05/08 13:55:56 Reading Terragrunt config file at /build/artifact/terraform.tfvars
[terragrunt] 2018/05/08 13:55:56 Downloading Terraform configurations from git::https://ghe.example.com/terraform/hello-world.git?ref=master into /root/.terragrunt/x_9QmmdMYIWoZ14uehJY1M6fGqU/MiQ5A_dvB0remey-dounjZgYyi4 using terraform init

[terragrunt] [/build/artifact] 2018/05/08 13:55:56 Initializing remote state for the local backend
[terragrunt] [/build/artifact] 2018/05/08 13:55:56 Detected 2 Hooks
[terragrunt] [/build/artifact] 2018/05/08 13:55:56 Running command: terraform init -from-module=git::https://ghe.example.com/terraform/hello-world.git?ref=master /root/.terragrunt/x_9QmmdMYIWoZ14uehJY1M6fGqU/MiQ5A_dvB0remey-dounjZgYyi4

[terragrunt] 2018/05/08 13:56:18 Copying files from /build/artifact into /root/.terragrunt/x_9QmmdMYIWoZ14uehJY1M6fGqU/MiQ5A_dvB0remey-dounjZgYyi4
[terragrunt] 2018/05/08 13:56:18 Setting working directory to /root/.terragrunt/x_9QmmdMYIWoZ14uehJY1M6fGqU/MiQ5A_dvB0remey-dounjZgYyi4
[terragrunt] 2018/05/08 13:56:18 Detected 2 Hooks

[terragrunt] 2018/05/08 13:56:18 Executing hook: before_hook_0
[terragrunt] 2018/05/08 13:56:18 Running command: ls -hal /build/artifact
drwxr-xr-x 2 root root 4.0K May  8 13:55 .
drwxr-xr-x 5 root root 4.0K May  8 13:55 ..
-rw-r--r-- 1 root root 1003 May  8 13:55 extra.auto.tfvars
-rw-r--r-- 1 root root  567 May  8 13:55 terraform.tfvars

[terragrunt] 2018/05/08 13:56:18 Executing hook: before_hook_1
[terragrunt] 2018/05/08 13:56:18 Running command: ls -hal
drwxr-xr-x 6 root root 4.0K May  8 13:56 .
drwxr-xr-x 3 root root 4.0K May  8 13:55 ..
drwxr-xr-x 4 root root 4.0K May  8 13:55 .terraform
-rw-r----- 1 root root   27 May  8 13:56 .terragrunt-source-version
-rw-r--r-- 1 root root 3.1K May  8 13:55 README.md
-rw-r--r-- 1 root root 1003 May  8 13:56 extra.auto.tfvars
-rw-r--r-- 1 root root 4.0K May  8 13:55 main.tf
-rw-r--r-- 1 root root  749 May  8 13:55 outputs.tf
-rw-r--r-- 1 root root  567 May  8 13:56 terraform.tfvars
-rw-r--r-- 1 root root 3.6K May  8 13:55 variables.tf
[terragrunt] 2018/05/08 13:56:18 Running command: terraform plan -out=/build/artifact/terraform.tfplan

<< Plan continues successfully >>
```

**Comment by brikis98** [comment] 2018-05-08 14:39
Duplicate of #394.

**Closed by brikis98** 2018-05-08 14:39 UTC

**Comment by brikis98** [comment] 2018-05-08 15:27
I suspect it's the same cause and requires the same fix though!
