### ISSUE TITLE
Enrich -all commands outputs

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [gruntwork-io/terragrunt#681] opened 2019-03-16 13:33 UTC
Hi!

Currently when you want to run any *-all command Terragrunt prints outputs and when some problem/change occurs, you need to study whole log of all modules - it's quite problematic in my case for example, because i have about 15 components and output is very big and messy. 

Additionally apply/destroy when some components fails print message like 
```plaintext
Hit multiple errors:
exit status 1
exit status 1
exit status 1
```

So what do you think about improvements like:
1. Better error messages - pass context to error handler to at least print which module failed with error - and in result print better *multiple error* output
2. Better plan messages - similar idea to errors - pass context and show which modules are changed at the end of log
2. Create log-file/component for faster navigation between plan/error logs

I'm not sure if I'm able to implement it - I'm not into Go, but i can try ;P

**Comment by brikis98** [comment] 2019-03-18 13:17
Completely agree. PR(s) to improve this functionality are very welcome 👍 

I'm going to close this issue as a duplicate of https://github.com/gruntwork-io/terragrunt/issues/78, https://github.com/gruntwork-io/terragrunt/issues/80, and https://github.com/gruntwork-io/terragrunt/issues/74, all of which came earlier.

**Closed by brikis98** 2019-03-18 13:17 UTC
