### ISSUE TITLE
Terragrunt Not Finding SSO Credentials 

### ISSUE THREAD

**Issue by kleidcmp** [gruntwork-io/terragrunt#1599] opened 2021-03-19 18:50 UTC
I can't reopen issues, this is a carry forward from #1129.

# Environment

My `~/.aws/config`:

```
[default]
region = us-east-1

[profile AdministratorAccess-ACCT]
sso_start_url = https://mysso.awsapps.com/start
sso_region = us-east-1
sso_account_id = ACCT
sso_role_name = AdministratorAccess
region = us-east-1
output = json
```

My shell: 
```
$ echo $AWS_PROFILE
AdministratorAccess-ACCT

$ aws sts get-caller-identity
{
    "UserId": "A....m",
    "Account": "ACCT",
    "Arn": "arn:aws:sts::ACCT:assumed-role/AWSReservedSSO_AdministratorAccess_0....."
}
```

Versions:
```
$ terraform -version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.29.0
...
$ terragrunt -version
terragrunt version v0.28.11
```

# Experience

```
$ terragrunt init
ERRO[0006] /home..../terragrunt.hcl:4,46-65: Error in function call; Call to function "get_aws_account_id" failed: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors. 
ERRO[0006] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
```
The `terragrunt.hcl` in question has:

```
remote_state {
  backend = "s3"
  config = {
    bucket         = "terraform-state-${get_aws_account_id()}"
    key            = "my_project/${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-state"
  }
}
```

**Comment by brikis98** [comment] 2021-03-22 10:27
Thanks for reporting. We are too buried to dig into this right now, so if anyone has some cycles and can figure out what the issue is, a PR is very welcome!

**Comment by michelzanini** [comment] 2021-04-05 10:14
Have you tried adding `profile` to your remove_state configuration?

```
remote_state {
  backend = "s3"
  config = {
    bucket         = "terraform-state-${get_aws_account_id()}"
    key            = "my_project/${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-state"
    profile          = "AdministratorAccess-ACCT"
  }
}
```

This works for me.

**Comment by crablab** [comment] 2021-04-19 14:35
I am seeing this as well. My `terragrunt.hcl` is as follows: 

```
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    profile = "default"
    bucket  = "project-dev-terraform-state"
    key     = "dev/${path_relative_to_include()}/terraform.tfstate"
    region  = "eu-west-1"
    encrypt = true
    profile = "project"
  }
}
```

And the debug output is: 
```
[terragrunt] 2021/04/19 15:32:00 Terragrunt Version: v0.26.2
[terragrunt] 2021/04/19 15:32:00 Did not find any locals block: skipping evaluation.
[terragrunt] [...] 2021/04/19 15:32:00 Running command: terraform --version
[terragrunt] 2021/04/19 15:32:01 Terraform version: 0.14.8
[terragrunt] 2021/04/19 15:32:01 Reading Terragrunt config file at ...
[terragrunt] 2021/04/19 15:32:01 Did not find any locals block: skipping evaluation.
[terragrunt] 2021/04/19 15:32:01 The file path .../terraform/enviroments/dev/backend.tf already exists and if_exists for code generation set to "overwrite". Regenerating file.
[terragrunt] 2021/04/19 15:32:01 Generated file .../terraform/enviroments/dev/backend.tf.
[terragrunt] [.../terraform/enviroments/dev] 2021/04/19 15:32:01 Backend config has changed (Set environment variable TG_LOG=debug to have terragrunt log the changes)
[terragrunt] [.../supplier-portal/terraform/enviroments/dev] 2021/04/19 15:32:01 Changed from map[access_key:<nil> acl:<nil> assume_role_duration_seconds:<nil> assume_role_policy:<nil> assume_role_policy_arns:<nil> assume_role_tags:<nil> assume_role_transitive_tag_keys:<nil> bucket:project-dev-terraform-state dynamodb_endpoint:<nil> dynamodb_table:<nil> encrypt:%!s(bool=true) endpoint:<nil> external_id:<nil> force_path_style:<nil> iam_endpoint:<nil> key:dev/./terraform.tfstate kms_key_id:<nil> max_retries:<nil> profile:default region:eu-west-1 role_arn:<nil> secret_key:<nil> session_name:<nil> shared_credentials_file:<nil> skip_credentials_validation:<nil> skip_metadata_api_check:<nil> skip_region_validation:<nil> sse_customer_key:<nil> sts_endpoint:<nil> token:<nil> workspace_key_prefix:<nil>] to map[bucket:project-dev-terraform-state encrypt:%!s(bool=true) key:dev/./terraform.tfstate profile:project region:eu-west-1]
[terragrunt] [.../supplier-portal/terraform/enviroments/dev] 2021/04/19 15:32:01 Initializing remote state for the s3 backend
[terragrunt] 2021/04/19 15:32:07 Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[terragrunt] 2021/04/19 15:32:07 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

As you can see, I'm running Terragrunt 0.14.8 and Terraform 0.26.2. I've removed some paths with internal names in them. 

I did also set `AWS_PROFILE` but it seems Terragrunt is expecting 'actual' credentials to check/create the state bucket.

**Comment by ryno75** [comment] 2021-04-21 13:09
If you are using an AWS SSO profile you will need to upgrade to Terragrunt 0.28.9 or later.  [SSO wasn't supported until 0.28.9](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.9) and is why you are seeing this error.  Related to #1129, #1537 

Though I will say... there appears to still be an issue with setting the remote_state bucket policy/parameters when using an AWS SSO profile.  I will be opening an issue for that.

**Comment by crablab** [comment] 2021-04-21 13:38
> Though I will say... there appears to still be an issue with setting the remote_state bucket policy/parameters when using an AWS SSO profile. I will be opening an issue for that.

Agreed. This is what I observed after updating my versions.

**Comment by yorinasub17** [comment] 2021-04-27 17:31
Closing as we now have the follow up ticket for the specific issue reported above: https://github.com/gruntwork-io/terragrunt/issues/1650

**Closed by yorinasub17** 2021-04-27 17:31 UTC
Labels: bug, help wanted
