### ISSUE TITLE
Unable to determine underlying exit code

### ISSUE THREAD

**Issue by sitilge** [gruntwork-io/terragrunt#1363] opened 2020-09-19 19:09 UTC
I am running:

- alpine:latest container, 5.8.9-arch kernel
- terraform 0.13.3
- terragrunt 0.25.0

I am getting the following error, when running a shared GitLab worker:
```
$ terragrunt plan --terragrunt-working-dir asg
[terragrunt] [asg] 2020/09/19 18:40:47 Running command: terraform --version
[terragrunt] 2020/09/19 18:40:47 fork/exec /usr/local/bin/terraform: exec format error
[terragrunt] 2020/09/19 18:40:47 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by brikis98** [comment] 2020-09-20 10:25
Not sure I follow... What Terragrunt command are you running? `terragrunt --version`?

**Comment by sitilge** [comment] 2020-09-20 16:51
@brikis98 yes, I updated the question. It was a typo.

**Comment by kwilczynski** [comment] 2020-09-20 22:57
Hi @sitilge, I am sorry you are having issues!

Personally, I am sadly unable to reproduce this when running `terragrunt --version` as per:

![Screenshot 2020-09-21 at 00 52 30](https://user-images.githubusercontent.com/250723/93724137-d087f200-fba4-11ea-8cad-cffa6fcbfd0d.png)

There is nothing special about `--version` command-line switch.

How was your Terragrunt binary installed?

**Comment by brikis98** [comment] 2020-09-21 07:57
Same here... I can't repro this:

```
$ terragrunt --version
terragrunt version v0.25.0
```

**Comment by sitilge** [comment] 2020-09-21 09:02
I updated with the exact output.

@kwilczynski I am doing it in a Dockerfile, that is built by a GitLab worker:

> #A one-liner to get the latest Terraform binary
RUN URL="https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_linux_amd64.zip" \
 && curl -o terraform.zip -L $URL \
 && unzip terraform.zip \
 && chmod +x terraform

**Comment by kwilczynski** [comment] 2020-09-21 16:15
Hi @sitilge, thank you for updating the initial log to include the error you are seeing.

Just to clarify - this is not really related to Terragrunt or running `terragrunt --version`. Your updated message clarified that.

Now, the crucial bit of information from the error output is the following:

```
[terragrunt] 2020/09/19 18:40:47 fork/exec /usr/local/bin/terraform: exec format error
```

Terragrunt runs Terraform as part of the `terragrunt plan`, but the Terraform binary at `/usr/local/bin/terraform` causes a failure that then bubbles up to Terragrunt as it can be run on the underlying platform. Commonly, such message can be see if one of the following happens:

- Binary is for _wrong platform_ e.g., **x86** vs **ARM** (Linux vs Darwin)
- Binary is for _wrong architecture_ e.g., **x86** vs **x86_64** (32 bit vs 64 bit)
- Binary is a dynamic binary and loader/linker (ld) is _unable to resolve symbols_ this binary requires from libraries it was linked with (e.g., libraries are missing or incompatible version is installed, wrong rpath, etc.) i.e., Go binary build with `CGO_ENABLED` set to `1` and libc is at different location than what the rpath would suggest

Make sure that the platform and the architecture match that of the Terraform binary you are downloading.

**Comment by sitilge** [comment] 2020-09-21 16:53
Yes, the platform is using x86_64 GNU/Linux, which matches the binary I was getting.

I rebuilt the parent image:

```
Step 11/12 : RUN terraform --version
 ---> Running in 73ac265c02ec
Terraform v0.13.3
Removing intermediate container 73ac265c02ec
 ---> 5b5f98071bad
Step 12/12 : RUN terragrunt --version
 ---> Running in 6278b3aca33f
terragrunt version v0.25.1
```

and it works now... I don't know really what it was, but it works with terragrunt 0.25.1.

**Comment by brikis98** [comment] 2020-09-24 08:35
Thanks for digging into these! Looks like this was a Terraform binary issue that's now solved, so closing.

**Closed by brikis98** 2020-09-24 08:35 UTC
Labels: question
