### ISSUE TITLE
0.18.7 segfaults on 2021 Mac M1 12.1 Monterey

### ISSUE THREAD

**Issue by jonassteinberg1** [gruntwork-io/terragrunt#2125] opened 2022-05-26 13:38 UTC
# Steps to repro

```
mkdir ~/.tgenv/versions/0.18.7

wget -q -O ~/.tgenv/versions/0.18.7/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.18.7/terragrunt_darwin_amd64

chmod +x ~/.tgenv/versions/0.18.7/terragrunt 

 ~/.tgenv/versions/0.18.7/terragrunt -v                                                                                 ✔
[1]    50196 segmentation fault  ~/.tgenv/versions/0.18.7/terragrunt -v
```

# works fine on linux (naturally)

```
root@a903991446ed:/# mkdir ~/.tgenv/versions/0.18.7
root@a903991446ed:/# wget -q -O ~/.tgenv/versions/0.18.7/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.18.7/terragrunt_linux_amd64
root@a903991446ed:/# ls -la ~/.tgenv/versions/0.18.7/terragrunt
-rw-r--r-- 1 root root 18591788 Dec  8 05:07 /root/.tgenv/versions/0.18.7/terragrunt
root@a903991446ed:/# chmod +x /root/.tgenv/versions/0.18.7/terragrunt
root@a903991446ed:/# chmod 777 /root/.tgenv/versions/0.18.7/terragrunt
root@a903991446ed:/# tgenv use 0.18.7
Switching default version to v0.18.7
Switching completed
root@a903991446ed:/# terragrunt -v
terragrunt version v0.18.7
root@a903991446ed:/# chmod +x /root/.tgenv/versions/0.18.7/terragrunt
root@a903991446ed:/# tgenv use 0.18.7
Switching default version to v0.18.7
Switching completed
root@a903991446ed:/# terragrunt -v
terragrunt version v0.18.7
```

any advice would be greatly appreciated.

**Comment by yorinasub17** [comment] 2022-05-26 14:14
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/1432

Unfortunately this is not something we are able to handle at the moment. The best is to use docker or a linux environment. You can also try using https://github.com/denis256/terragrunt/releases/tag/v0.18.7 . Note that this is provided from a member of our team (so is legit), but has not been tested thoroughly (so there may be bugs). Use with caution.

Closing as dup/won't fix.

**Closed by yorinasub17** 2022-05-26 14:14 UTC

**Comment by jonassteinberg1** [comment] 2022-05-26 14:45
Amazing recommendation.  Thanks.  Seems like this will work.
