### ISSUE TITLE
Multi Level Before/After Hooks

### ISSUE THREAD

**Issue by vaibhavkhurana2018** [gruntwork-io/terragrunt#1700] opened 2021-06-03 10:22 UTC
I have a use case where i want to run hooks at the root level and then at individual env level. The structure looks like below:

.
|-- prod
|   |-- vpc
|   |   `-- terragrunt.hcl
|   `-- terragrunt.hcl
|-- qa
|   |-- vpc
|   |   `-- terragrunt.hcl
|   `-- terragrunt.hcl
|-- stage
|   |-- vpc
|   |   `-- terragrunt.hcl
|   `-- terragrunt.hcl
`-- terragrunt.hcl

What i want to is have hooks configured on the root level terragrunt.hcl and other configurations along with env specific hooks in the respective environment directories. 

When trying this, i am getting the error Only one level of includes is allowed, which is also described in some other issues as well. But the issue talks over passing other variables but i am not able to do similar things with hooks. Can someone let me know if this is possible or some other approach to do this?

**Comment by brikis98** [comment] 2021-06-04 07:58
If you're getting an error about one level of includes, it's not about hooks, but about `include { ... }` blocks. Right now, Terragrunt only allows one level: i.e., a child with an include pointing at a parent. That parent cannot also have an `include { ... }` pointing at yet another parent.

**Comment by yorinasub17** [comment] 2021-09-27 21:20
Closing as duplicate of https://github.com/gruntwork-io/terragrunt/issues/303. Please follow that ticket if you are interested in that feature.

Side note, we now support multiple include blocks for a single level, which might be a viable workaround. Refer to [the terragrunt docs on the feature](https://terragrunt.gruntwork.io/docs/features/keep-your-terragrunt-architecture-dry/) for more info.

**Closed by yorinasub17** 2021-09-27 21:20 UTC
Labels: question
