### ISSUE TITLE
Extend auto-init to recognize more cases when `terraform init` is necessary

### ISSUE THREAD

**Issue by jubr** [gruntwork-io/terragrunt#1414] opened 2020-11-04 15:53 UTC
The recent merge of the [retryable_errors feature](https://github.com/gruntwork-io/terragrunt/pull/1232) got me 🤔 could a similar approach also work for detecting more cases where currently a `terraform init` needs to be performed manually. 

Currently [auto-init](https://terragrunt.gruntwork.io/docs/features/auto-init/) recognizes the following cases:
* terraform init has never been called, or
* source needs to be downloaded, or
* the modules or remote state used by the module have changed since the previous call to terraform init.

Here's an example output of `terragrunt plan` that currently needs manual intervention:
```
Error: Could not load plugin

Plugin reinitialization required. Please run "terraform init".
```
In my case I got here by adding a new provider in a `generate "providers" { }` block in `terragrunt.hcl` after `terragrunt init` had already been run, so auto-init does not catch it. I suppose there are more other ways to get here. I find I'm running into this quite regularly in my dev workflow.

If this sounds like something that's doable, then it could be based on something along the lines of:
```terraform
auto_init_errors = [
  "(?s).*Could not load plugin.*",
]
```
or maybe even combine them with something like:
```terraform
retryable_errors = [
  { re: "(?s).*ssh_exchange_identification.*Connection closed by remote host.*", flags: ["retry"] },
  /* ... */
  { re: "(?s).*Could not load plugin.*", flags: ["auto-init", "retry"] },
]
```

What do you guys think?

**Comment by brikis98** [comment] 2020-11-05 08:55
Agreed! I believe this is a duplicate of #388, so I will close this issue. @kwilczynski started implementing it in #1334, but hit some issues, and I'm guessing ran out of time, if anyone wants to pick that up again and finish it up!

**Closed by brikis98** 2020-11-05 08:55 UTC
