### ISSUE TITLE
BUG: cannot escape ${ in complex data structures

### ISSUE THREAD

**Issue by jeffreymlewis** [gruntwork-io/terragrunt#2122] opened 2022-05-24 17:52 UTC
**Describe the bug**
Escaping `${` does not work properly inside complex data structures.

**To Reproduce**
Terragrunt version `v0.37.1`

First you need a terraform module with a complex data structure.

```hcl
variable "test_var" {
  type = any
}

output "test_var" {
  value = var.test_var
}
```

Then try to escape a `${` in your `terragrunt.hcl`.

```
inputs = {
  test_var = {
    jlewis = {
      container_definitions = {
        command = "$${GITHUB_TOKEN}"
      }
    }
  }
}
```

Terragrunt output will be.

```
│ Error: Variables not allowed
│ 
│   on <value for var.test_var> line 1:
│   (source code not available)
│ 
│ Variables may not be used here.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 1:
│    1: variable "test_var" {
│ 
│ The root module input variable "test_var" is not set, and has no default
│ value. Use a -var or -var-file command line argument to provide a value for
│ this variable.
╵
ERRO[0016] 1 error occurred:
        * exit status 1
          
exit status 1
``` 

**Expected behavior**
I expected the following output.

```
Changes to Outputs:
  + test_var = {
      + jlewis = {
          + container_definitions = {
              + command = "$${GITHUB_TOKEN}"
            }
        }
    }
```

**Nice to have**
- [X] Terminal output
- [ ] Screenshots

**Additional context**

```
terragrunt version v0.37.1
```

**Comment by yorinasub17** [comment] 2022-05-24 18:15
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/1658

As indicated in that issue, the workaround for this is to add another `$`, since what you want to render to terraform is `$$`, e.g. `$$${GITHUB_TOKEN}`

**Closed by yorinasub17** 2022-05-24 18:15 UTC
