### ISSUE TITLE
get a output from one module into another

### ISSUE THREAD

**Issue by P3BKAC** [gruntwork-io/terragrunt#831] opened 2019-08-12 22:11 UTC
I am trying a greenfield deployment using terragrunt. I am trying to pass the output of one module into another.

in native terraform it would just be module.name.output_var

I don't see a way to get the output of a module into a variable that can be used else ware.  What am I missing?

**Comment by yorinasub17** [comment] 2019-08-12 22:29
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/418. Refer to the thread on the issue for various workarounds. Note that this is actively being implemented in https://github.com/gruntwork-io/terragrunt/pull/828.

**Closed by yorinasub17** 2019-08-12 22:29 UTC
